### ISSUE TITLE
Uncaught TypeError: this.ink.Console.fromId is not a function

### ISSUE THREAD

**Issue by hugos94** [JunoLab/atom-julia-client#103]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.3.1

### Stack Trace

Uncaught TypeError: this.ink.Console.fromId is not a function

```
At /Users/HugoPiauilino/julia-client/lib/ui/console.coffee:34

TypeError: this.ink.Console.fromId is not a function
    at Object.module.exports.create (/Users/HugoPiauilino/julia-client/lib/ui/console.coffee:34:23)
    at Object.module.exports.activate (/Users/HugoPiauilino/julia-client/lib/ui/console.coffee:10:6)
    at Object.module.exports.consumeInk (/Users/HugoPiauilino/julia-client/lib/ui.coffee:18:14)
    at Object.module.exports.JuliaClient.consumeInk (/Users/HugoPiauilino/julia-client/lib/julia-client.coffee:24:7)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.pyc",
      "*.DS_Store"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.3.2
julia-client, v0.3.1
language-julia, v0.5.0
language-latex, v0.6.1
latex, v0.29.0

# Dev
No dev packages
```

**Comment by one-more-minute** [comment]
It looks like you're on master of julia-client but not up to date with ink – can you try pulling the latest ink code?

**Comment by one-more-minute** [comment]
Will assume this is sorted, but let me know if I can help further.
