### ISSUE TITLE
Uncaught TypeError: this.jlpath is not a function

### ISSUE THREAD

**Issue by ashwincarvalho** [JunoLab/atom-julia-client#106]
Getting this error when trying to start a REPL client from Atom:

**Atom Version**: 1.5.1
**System**: Mac OS X 10.9.5
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.3.1

### Stack Trace

Uncaught TypeError: this.jlpath is not a function

```
At /Users/Ty/.atom/packages/julia-client/lib/connection/terminal.coffee:38

TypeError: this.jlpath is not a function
    at Object.module.exports.client (/Users/Ty/.atom/packages/julia-client/lib/connection/terminal.coffee:38:24)
    at /Users/Ty/.atom/packages/julia-client/lib/package/commands.coffee:35:41
    at Object.module.exports.listen (/Users/Ty/Software/atom/julia-client/lib/connection/tcp.coffee:21:12)
    at /Users/Ty/.atom/packages/julia-client/lib/package/commands.coffee:35:15
    at Object.module.exports.disrequire (/Users/Ty/.atom/packages/julia-client/lib/connection/client.coffee:132:43)
    at atom-workspace.subs.add.atom.commands.add.julia-client:start-repl-client (/Users/Ty/.atom/packages/julia-client/lib/package/commands.coffee:34:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:32.5.0 julia-client:open-a-repl (atom-text-editor.editor)
     -0:22.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:20.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -0:19.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:17.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.2.0 julia-client:clear-console (atom-text-editor.editor)
     -0:16.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 10x -0:15.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:10.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:10.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.1.0 julia:open-julia-home (atom-text-editor.editor)
     -0:07.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 10x -0:05.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:01.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 julia-client:start-repl-client (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "language-matlab-octave"
    ]
  },
  "julia-client": {
    "juliaPath": "/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin/julia"
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.3.2
julia-client, v0.3.1
language-julia, v0.5.0
language-matlab, v0.1.1
latex-completions, v0.3.0

# Dev
No dev packages
```

**Comment by one-more-minute** [comment]
Are you on master branches of any of these packages? Either way, this will be fixed for sure when 0.4 is out.
