### ISSUE TITLE
Failed to load the julia-client package: Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#110]
I'm on master for julia-client and ink.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.3.1

### Stack Trace

Failed to load the julia-client package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/solver/Projects/julia-client/lib/runtime/modules.coffee:2:14)
    at Object.<anonymous> (/Users/solver/Projects/julia-client/lib/runtime/modules.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/solver/Projects/julia-client/lib/runtime.coffee:2:15)
    at Object.<anonymous> (/Users/solver/Projects/julia-client/lib/runtime.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/solver/Projects/julia-client/lib/julia-client.coffee:8:15)
    at Object.<anonymous> (/Users/solver/Projects/julia-client/lib/julia-client.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "julia-client": {}
}
```

### Installed Packages

```coffee
# User
ink, v0.3.2
julia-client, v0.3.1
language-julia, v0.5.0
latex-completions, v0.3.1
minimap, v4.19.0
minimap-autohide, v0.10.1
number-slider, v1.0.1
project-manager, v2.7.6

# Dev
No dev packages
```

**Comment by Varanas** [comment]
`apm install` in the `julia-client` dir should do the trick -- `underscore-plus` is a new dependency.

**Comment by dlfivefifty** [comment]
Thanlks, look like that worked
