### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by DatName** [JunoLab/atom-julia-client#113]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0-beta4
**System**: Ubuntu 14.04.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined

```
At ~/.atom/packages/julia-client/lib/misc/history.coffee:27

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Interface.<anonymous> (~/.atom/packages/julia-client/lib/misc/history.coffee:27:19)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at ReadStream.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1754:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "julia-client": {
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.3.2
julia-client, v0.3.1
language-julia, v0.5.0

# Dev
No dev packages
```

**Comment by MikeInnes** [comment]
Thanks for reporting. Are you on master on any of the packages?

Also, what's the state of your `~/.julia_history` file?

**Comment by DatName** [comment]
Well, I just deleted .julia_history file. _This resolved the issue._
Julia itself were saying (on startup, in konsole) that my .history_file was too old and need to be deleted. Until now I ignored this message. 
Thank you for the tip and a quick reply.

**Comment by MikeInnes** [comment]
Ah ok, thanks for letting me know. Juno clearly isn't handling old history file formats properly, so that's something to earmark for the future.

**Comment by therimalaya** [comment]
```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7


### Stack Trace

Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined

```
At /home/parallels/.atom/packages/julia-client/lib/misc/history.coffee:27

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Interface.<anonymous> (/home/parallels/.atom/packages/julia-client/lib/misc/history.coffee:27:19)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at ReadStream.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1832:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

### Commands

```
  2x -0:56.3.0 core:close (atom-pane.pane.active)
     -0:51.5.0 settings-view:open (atom-pane.pane.active)
     -0:44.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.4.4
julia-client, v0.4.7
language-julia, v0.6.0
latex-completions, v0.3.1
tool-bar, v1.0.0
uber-juno, v0.1.1

# Dev
No dev packages
```

Got into similar issue, the solution above is not working for me!!

**Comment by emirion** [comment]
I had similar problem. I uninstalled the julia-client from atom and deleted the julia-client from ~/.atom/packages/ manually, and installed the package again, worked for me!
