### ISSUE TITLE
Uncaught TypeError: Cannot read property 'working' of undefined

### ISSUE THREAD

**Issue by maunke** [JunoLab/atom-julia-client#116]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'working' of undefined

```
At /home/maunke/.atom/packages/julia-client/lib/connection/client.coffee:99

TypeError: Cannot read property 'working' of undefined
    at Object.module.exports.booting (/home/maunke/.atom/packages/julia-client/lib/connection/client.coffee:99:13)
    at Object.module.exports.jlprocess.start (/home/maunke/.atom/packages/julia-client/lib/connection/process.coffee:66:12)
    at /home/maunke/.atom/packages/julia-client/lib/package/commands.coffee:38:40
    at Server.<anonymous> (/home/maunke/.atom/packages/julia-client/lib/connection/tcp.coffee:41:7)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1257:10)
    at doNTCallback1 (node.js:430:9)
    at process._tickCallback (node.js:352:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "script"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "julia-client": {
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.2
atom-material-ui, v0.8.1
julia-client, v0.3.1
language-julia, v0.5.0
language-latex, v0.6.1
linter, v1.11.3
linter-csslint, v1.3.1
linter-htmlhint, v1.0.2
linter-jshint, v2.0.2
minimap, v4.19.0
minimap-pigments, v0.1.7
pigments, v0.24.1
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by dr-seth** [comment]
I am currently having this is issue, yet it is marked as resolved
