### ISSUE TITLE
Failed to activate the julia-client package

### ISSUE THREAD

**Issue by GravityAssisted** [JunoLab/atom-julia-client#117]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.1
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.3.1
### Stack Trace

Failed to activate the julia-client package

```
At Cannot find module './completions'

Error: Cannot find module './completions'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.JuliaClient.completions (/Users/arora/.atom/packages/julia-client/lib/julia-client.coffee:1:1)
    at Package.module.exports.Package.activateServices (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/package.js:347:69)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/package.js:184:16)
    at /opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -0:25.9.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "julia-client": {
    "juliaPath": "/Users/arora/src/julia//julia"
  }
}
```
### Installed Packages

``` coffee
# User
antialiased, v0.1.0
autocomplete-julia, v0.1.0
character-table, v0.4.3
ink, v0.3.2
julia-client, v0.3.1
language-cuda, v0.1.0
language-fortran, v2.0.9
language-julia, v0.5.0
language-latex, v0.6.1
language-matlab, v0.2.0
latex-completions, v0.3.1
linter, v1.11.3
minimap, v4.19.0
quick-highlight, v0.3.10

# Dev
No dev packages
```

**Comment by MikeInnes** [comment]
Strange. Does this still happen on 0.4? Did you install the package through Atom's package manager or via the git master?

**Comment by KareemSalah** [comment]
I have the same issue, here's stack trace
Error: Autocomplete provider 'Object(undefined)'
specifies `selector` instead of the `scopeSelector` attribute.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API.
  at ProviderManager.module.exports.ProviderManager.registerProvider (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/provider-manager.js:302:17)
  at ProviderManager.registerProvider (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/provider-manager.js:3:61)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:83:65
  at Object.module.exports.requireAutocompleteManagerAsync (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:23:49)
  at Object.module.exports.consumeProvider (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:79:12)
  at Object.module.exports.consumeProvider_3_0 (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:65:19)
  at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:352:71)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:186:16)
  at /usr/share/atom/resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at /usr/share/atom/resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at Pipe._onclose (net.js:477:12)

**Comment by MikeInnes** [comment]
What's your version of Atom?

**Comment by mkborregaard** [comment]
I have the same error being thrown on updating Atom packages. I am on Atom-1.9.8, ink is 0.5, I updated julia-client from 4.7 (I think) to 0.5, Julia is 0.4.6.

**Comment by KareemSalah** [comment]
The issue is just like what @mkborregaard has just said :D

**Comment by mkborregaard** [comment]
I did a lot of things - restarted Atom, installed julia-0.5, ran Pkg.update() in a terminal, pointed Atom to this, then restarted Atom again. Now everything works like a charm. Sorry for not being systematic in my bug-hunting.

**Comment by MikeInnes** [comment]
Great – yeah, I'm not sure why this is happening but making sure everything is up to date and restarting should resolve it.

**Comment by mkborregaard** [comment]
But now julia-client gives various intermittent (non-reproducible) errors:
```
UndefVarError: @doc_str not defined
 in filter!(::Atom.##110#113, ::Array{Symbol,1}) at ./array.jl:1389
 in (::Atom.##109#112)(::String) at /Users/michael/.julia/v0.5/Atom/src/eval.jl:188
 in handlemsg(::Dict{String,Any}, ::String, ::Vararg{String,N}) at /Users/michael/.julia/v0.5/Atom/src/comm.jl:71
 in (::Atom.##5#8)() at ./event.jl:68
```

and 
```
UndefVarError: @with not defined
 in filter!(::Atom.##110#113, ::Array{Symbol,1}) at ./array.jl:1389
 in (::Atom.##109#112)(::String) at /Users/michael/.julia/v0.5/Atom/src/eval.jl:188
 in handlemsg(::Dict{String,Any}, ::String, ::Vararg{String,N}) at /Users/michael/.julia/v0.5/Atom/src/comm.jl:71
 in (::Atom.##5#8)() at ./event.jl:68
```

Meaning the julia-client throws the error on every input but not again after restarting.

**Comment by MikeInnes** [comment]
What's your `Pkg.status()` now?

**Comment by mkborregaard** [comment]
I cannot reproduce the error anymore. Perhaps this is the reason: I was using a script to load all available packages in order, to precompile them. As this was running, focus was returned to the console, and errors appeared as I typed in commands while this ran.
Now it has finished and errors do not appear. Sorry, this is hardly useful for bug-hunting. For the record, `Pkg.status`is 
```

24 required packages:
 - Atom                          0.5.0
 - Bio                           0.3.0
 - ColorBrewer                   0.3.0
 - DataFrames                    0.7.8
 - DataFramesMeta                0.1.3
 - Distributions                 0.10.2
 - FactCheck                     0.4.3
 - FileIO                        0.1.0
 - FreqTables                    0.0.2
 - GLM                           0.5.4
 - GLVisualize                   0.0.10
 - GR                            0.14.0
 - IJulia                        1.2.0
 - MixedModels                   0.5.5
 - NamedArrays                   0.5.1
 - PlotRecipes                   0.0.6
 - PlotlyJS                      0.3.1
 - Plots                         0.9.0
 - PyPlot                        2.2.1
 - RCall                         0.5.1
 - RecipesBase                   0.0.6
 - Shapefile                     0.0.3
 - StatPlots                     0.0.3
 - Stats                         0.1.0
109 additional packages:
 - ASTInterpreter                0.0.3
 - AbstractTrees                 0.0.3
 - ArgParse                      0.3.1
 - ArrayViews                    0.6.4
 - AutoHashEquals                0.0.10
 - BinDeps                       0.4.2
 - Blink                         0.4.0
 - Blosc                         0.1.6
 - BufferedStreams               0.1.6
 - COFF                          0.0.1
 - CRC                           1.1.1
 - Calculus                      0.1.15
 - Clustering                    0.5.0
 - CodeTools                     0.4.0
 - Codecs                        0.2.0
 - ColorTypes                    0.2.6
 - ColorVectorSpace              0.1.7
 - Colors                        0.6.6
 - Combinatorics                 0.3.2
 - Compat                        0.8.7
 - Compose                       0.4.3
 - Conda                         0.2.3
 - DWARF                         0.0.3
 - DataArrays                    0.3.8
 - DataStructures                0.4.5
 - Distances                     0.3.2
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - ELF                           0.0.3
 - FixedPointNumbers             0.1.4
 - FixedSizeArrays               0.2.2
 - ForwardDiff                   0.2.2
 - FreeType                      1.0.3
 - GLAbstraction                 0.1.0
 - GLFW                          1.1.3
 - GLWindow                      0.1.4
 - GZip                          0.2.20
 - Gallium                       0.0.3
 - GeometryTypes                 0.1.6
 - Graphics                      0.1.3
 - Grid                          0.4.2
 - HDF5                          0.6.5
 - Hiccup                        0.0.3
 - Homebrew                      0.3.4
 - HttpCommon                    0.2.6
 - HttpParser                    0.1.1
 - HttpServer                    0.1.6
 - Images                        0.5.8
 - IndexableBitVectors           0.1.1
 - IntervalTrees                 0.0.5
 - Iterators                     0.1.10
 - JLD                           0.6.3
 - JSON                          0.6.0
 - JuliaParser                   0.7.4
 - KernelDensity                 0.2.0
 - LNR                           0.0.2
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.0
 - LegacyStrings                 0.1.1
 - Libz                          0.2.0
 - LightGraphs                   0.5.4
 - LightXML                      0.3.0
 - MachO                         0.0.3
 - MacroEcology.jl               0.0.0-             master (unregistered)
 - MacroTools                    0.3.2
 - MathProgBase                  0.5.3
 - MbedTLS                       0.3.0
 - Measures                      0.0.3
 - Media                         0.2.1
 - MeshIO                        0.0.5
 - ModernGL                      0.0.8
 - Mustache                      0.0.15
 - Mux                           0.2.1
 - NLopt                         0.3.2
 - NaNMath                       0.2.1
 - Nettle                        0.2.4
 - ObjFileBase                   0.0.3
 - Optim                         0.6.0
 - PDMats                        0.4.2
 - Packing                       0.0.4
 - ParserCombinator              1.7.11
 - PlotUtils                     0.0.4
 - Polynomials                   0.0.6
 - PositiveFactorizations        0.0.2
 - Primes                        0.1.1
 - PyCall                        1.7.1
 - Quaternions                   0.1.1
 - Reactive                      0.3.4
 - Reexport                      0.0.3
 - Requires                      0.3.0
 - Rmath                         0.1.2
 - Roots                         0.2.1
 - SHA                           0.2.1
 - SIUnits                       0.0.6
 - Showoff                       0.0.7
 - SignedDistanceFields          0.0.1
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.8.3
 - StatsFuns                     0.3.0
 - StructIO                      0.0.2
 - TerminalUI                    0.0.2
 - TexExtensions                 0.0.3
 - TextWrap                      0.1.6
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WebSockets                    0.2.1
 - WoodburyMatrices              0.2.0
 - ZMQ                           0.3.4
 - Zlib                          0.1.12
```

**Comment by geekyI** [comment]
>It may be that simply restarting Atom was sufficient to clear the bug

Can confirm, I just did this simply; without upgrading julia or any other packages. Only updated the atom packages (`atom-julia-client` and `atom-ink`)

Related error atom-ink#40 was thrown

**Comment by geekyI** [comment]
`Pkg.status()` shows:
```
9 required packages:
 - Atom                          0.4.4
 - DataFrames                    0.7.8
 - Gadfly                        0.4.2
 - ImageMagick                   0.1.7
 - ImageView                     0.1.20
 - Images                        0.5.8
 - PlotlyJS                      0.3.1
 - Plots                         0.8.2
 - UnicodePlots                  0.1.4
69 additional packages:
 - BinDeps                       0.4.2
 - Blink                         0.3.4
 - Cairo                         0.2.34
 - Calculus                      0.1.15
 - CodeTools                     0.3.1
 - Codecs                        0.2.0
 - ColorTypes                    0.2.5
 - ColorVectorSpace              0.1.6
 - Colors                        0.6.6
 - Compat                        0.8.6
 - Compose                       0.4.2
 - Contour                       0.1.1
 - DataArrays                    0.3.8
 - DataStructures                0.4.5
 - Dates                         0.4.4
 - Distances                     0.3.2
 - Distributions                 0.10.2
 - DualNumbers                   0.2.2
 - FactCheck                     0.4.3
 - FileIO                        0.1.0
 - FixedPointNumbers             0.1.4
 - FixedSizeArrays               0.2.2
 - GZip                          0.2.20
 - Graphics                      0.1.3
 - Grid                          0.4.2
 - Hexagons                      0.0.4
 - Hiccup                        0.0.3
 - HttpCommon                    0.2.6
 - HttpParser                    0.1.1
 - HttpServer                    0.1.6
 - IniFile                       0.2.5
 - Iterators                     0.1.10
 - JSON                          0.6.0
 - JuliaParser                   0.6.4
 - KernelDensity                 0.2.0
 - LNR                           0.0.2
 - Lazy                          0.11.0
 - LegacyStrings                 0.1.1
 - LibExpat                      0.2.0
 - Loess                         0.0.7
 - MacroTools                    0.3.2
 - MbedTLS                       0.2.6
 - Measures                      0.0.3
 - Media                         0.2.1
 - Mustache                      0.0.15
 - Mux                           0.2.1
 - NaNMath                       0.2.1
 - Optim                         0.5.0
 - PDMats                        0.4.2
 - PlotUtils                     0.0.4
 - PositiveFactorizations        0.0.2
 - RecipesBase                   0.0.6
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - Rmath                         0.1.2
 - SHA                           0.2.0
 - SIUnits                       0.0.6
 - Showoff                       0.0.7
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.0
 - TexExtensions                 0.0.3
 - Tk                            0.3.8
 - URIParser                     0.1.6
 - WebSockets                    0.2.0
 - WinRPM                        0.2.0
 - Winston                       0.11.13
 - WoodburyMatrices              0.2.0
 - Zlib                          0.1.12
```

**Comment by pfitzseb** [comment]
I'm pretty sure this is not an issue anymore.
