### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by mkborregaard** [JunoLab/atom-julia-client#14]
1. Installed atom binary
2. Built Julia from the Master branch (that is v 0.4)
3. installed Julia to a folder on my path
4. Julia now works from the terminal, but atom's julia client cannot see it
5. Specify the path to the executable in julia-client options '/Users/michael/Documents/github/julia/usr/bin'
6. 'Toggle console', then write 2 + 2

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.1.2

### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1145

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at Object.module.exports.start (/Users/michael/.atom/packages/julia-client/lib/connection/process.coffee:12:21)
  at /Users/michael/.atom/packages/julia-client/lib/julia-client.coffee:82:40
  at Server.<anonymous> (/Users/michael/.atom/packages/julia-client/lib/connection/tcp.coffee:40:7)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1192:12
  at process._tickCallback (node.js:357:13)

```

### Commands

```
  3x -0:12.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.3.0 julia-client:toggle-console (atom-text-editor.editor)
     -0:00.8.0 console:evaluate (atom-text-editor.editor.is-focused)
     -0:00.8.0 julia-client:start-julia (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "julia-client": {
    "juliaPath": "/Users/michael/Documents/github/julia/usr/bin"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
ink, v0.1.1
julia-client, v0.1.2
language-julia, v0.4.1
language-r, v0.2.0

# Dev
No dev packages
```

**Comment by one-more-minute** [comment]
Looks like your `juliaPath` config is pointing at the `bin` folder rather than the `julia` executable inside – appending `/julia` should do the trick.

**Comment by mkborregaard** [comment]
Thanks, sorry.

**Comment by one-more-minute** [comment]
No problem, glad to help!
