### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activate' of undefined

### ISSUE THREAD

**Issue by chriscoey** [JunoLab/atom-julia-client#155]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7

### Stack Trace

Uncaught TypeError: Cannot read property 'activate' of undefined

```
At /Users/chris/.atom/packages/julia-client/lib/runtime/console.coffee:67

TypeError: Cannot read property 'activate' of undefined
    at Object.module.exports.open (/Users/chris/.atom/packages/julia-client/lib/runtime/console.coffee:67:7)
    at /Users/chris/.atom/packages/julia-client/lib/package/commands.coffee:69:72
    at Object.module.exports.withInk (/Users/chris/.atom/packages/julia-client/lib/package/commands.coffee:99:7)
    at atom-workspace.subs.add.atom.commands.add.julia-client:open-console (/Users/chris/.atom/packages/julia-client/lib/package/commands.coffee:69:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:58.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
     -0:19.3.0 julia-client:run-file (atom-text-editor.editor.is-focused)
     -0:19.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:19.3.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
     -0:11.5.0 julia-client:run-file (atom-text-editor.editor.is-focused)
     -0:11.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:11.5.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
  2x -0:07.1.0 julia-client:open-console (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "julia-ide",
      "autocomplete-julia",
      "autocomplete-python"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "julia-client": {
    "juliaPath": "/Applications/Julia-0.4.3.app/Contents/Resources/julia/bin/julia"
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.4.4
julia-client, v0.4.7
language-julia, v0.6.0
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by MikeInnes** [comment]
Have you tried restarting atom? The package updates have made quite a few internal changes so you're probably just in a weird state.

**Comment by chriscoey** [comment]
Thanks, yeah I should have tried that.
