### ISSUE TITLE
Uncaught Error: Object has been destroyedError: Object has been destroyed    at Error (native)...

### ISSUE THREAD

**Issue by spencerlyon2** [JunoLab/atom-julia-client#156]
[Enter steps to reproduce below:]

1. Open any Blink window
2. close the window

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7

### Stack Trace

Uncaught Error: Object has been destroyed
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:316:61)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:113

Error: Object has been destroyed
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:316:61)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:113:13)
    at BrowserWindow.get [as id] (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:229:14)
    at /Users/sglyon/.atom/packages/julia-client/lib/runtime/frontend.coffee:26:41
    at CallbacksRegistry.apply (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/common/api/lib/callbacks-registry.js:58:39)
    at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:236:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
  2x -0:27.3.0 proton:toggle (atom-text-editor.editor.is-focused)
     -0:25.9.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:25.9.0 console:evaluate (atom-text-editor.editor.is-focused)
     -0:16.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:13.3.0 proton:toggle (atom-text-editor.editor.is-focused)
     -0:12.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:12.6.0 console:evaluate (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:09.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:09.6.0 console:evaluate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "relative-numbers",
      "go-plus",
      "tester-go",
      "go-config",
      "gometalinter-linter",
      "go-get",
      "autocomplete-go",
      "gofmt",
      "go-debug",
      "navigator-godef",
      "gorename",
      "floobits",
      "asciidoc-preview",
      "Jude",
      "linter",
      "linter-markdown",
      "linter-pep8",
      "linter-rust",
      "project-manager",
      "minimap"
    ],
    "themes": [
      "isotope-ui",
      "tomorrow-night-eighties-syntax"
    ]
  },
  "julia-client": {
    "errorsToConsole": true
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.9
atom-alignment, v0.12.1
atom-slack-snippets, v0.2.0
atomatigit, v1.5.5
autocomplete-bibtex, v0.6.2
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
autoupdate-packages, v1.3.1
battery-status, v0.11.0
build, v0.60.0
build-cargo, v0.14.0
build-make, v0.9.0
easy-motion-redux, v1.1.0
environment, v1.2.0
file-icons, v1.7.8
highlight-line, v0.11.1
highlight-selected, v0.11.2
ink, v0.4.4
isotope-ui, v2.7.1
julia-client, v0.4.7
language-diff, v0.4.0
language-julia, v0.6.0
language-latex, v0.6.1
language-matlab-only, v0.2.0
language-rust, v0.4.6
last-cursor-position, v0.9.0
latex-completions, v0.3.0
latexer, v0.3.0
markdown-preview-plus, v2.4.0
markdown-scroll-sync, v2.1.2
markdown-writer, v2.3.3
merge-conflicts, v1.4.2
nvatom, v0.10.0
pdf-view, v0.50.0
project-plus, v0.8.2
proton-mode, v0.9.0
python-isort, v0.0.7
python-tools, v0.6.7
python-yapf, v0.10.0
racer, v0.20.0
recent-files-fuzzy-finder, v0.2.4
release-notes, v0.53.0
time-status, v1.1.2
tomorrow-night-eighties-syntax, v0.13.0
vim-mode, v0.65.0
vim-surround, v0.8.1
wakatime, v5.0.8
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by spencerlyon2** [comment]
Pretty much what happens is that if I open any blink window (e.g. through PlotlyJS) and then close it, Atom gives a big nasty error saying we destroyed an object. 

Sorry I don't have time to dig in right now to see what's going on, but I thought I'd post it to see if anyone else knows what the issue is right away.
