### ISSUE TITLE
Uncaught TypeError: this.ink.Spinner is not a function

### ISSUE THREAD

**Issue by kleinash** [JunoLab/atom-julia-client#167]
[Enter steps to reproduce below:]

1. Go to Packages 
2. Search for julia-client
3. Hit update

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7

### Stack Trace

Uncaught TypeError: this.ink.Spinner is not a function

```
At /home/ashley/.atom/packages/julia-client/lib/ui.coffee:19

TypeError: this.ink.Spinner is not a function
    at Object.module.exports.consumeInk (/home/ashley/.atom/packages/julia-client/lib/ui.coffee:19:20)
    at Object.module.exports.JuliaClient.consumeInk (/home/ashley/.atom/packages/julia-client/lib/julia-client.coffee:25:7)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
 16x -1:28.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 33x -1:14.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:10.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -0:58.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:53.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 17x -0:46.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/ashley/GIT"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-julia, v0.1.0
autocomplete-python, v1.7.2
build, v0.59.0
build-tools, v4.4.0
ink, v0.4.4
instant-build, v0.4.0
julia-client, v0.4.7
language-julia, v0.6.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
This shouldn't come up again after you restart Atom. 
So while this is a bug, it shouldn't actually matter much and only happens on that specific update, I think.

**Comment by kleinash** [comment]
Alrighty
