### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#18]
This seems to happen whenever I move the cursor inside my file, or really try to do much of anything.

I set a breakpoint in tcp.coffee:12 in the buffer method, and it looks like the data coming back over the socket was:
`"[20,{"inactive":false,"sub":"AudioIO","subInactive":true,"main":"Main"}]"`

I stepped through the code:
```coffee
      lines = str.split '\n'
      buffer[0] += lines.shift()
      buffer.push lines...
      while buffer.length > 1
        f buffer.shift()
```

and after `buffer[0] += lines.shift()` it looks like buffer is a 9-element array where the first element is the entire payload listed above, and then there are 8 empty strings. The first call to `f buffer.shift()` works fine but the 2nd one (where the first element of `buffer` is `""`) causes this exception. I think this is actually a result of a previous error which I'm digging into separately, and it seems that the buffer object is accumulating empty strings. I'll file an issue on that soon.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.1.2

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fsrussell%2F.julia%2Fv0.4%2FAudioIO%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.11%22%2C%22shellLoadTime%22%3A781%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fsrussell%2F.julia%2Fv0.4%2FAudioIO%22%5D%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Users/srussell/dotfiles/.atom/packages/julia-client/lib/connection/tcp.coffee:36:27
  at Socket.<anonymous> (/Users/srussell/dotfiles/.atom/packages/julia-client/lib/connection/tcp.coffee:17:9)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
     -3:41.6.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:38.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:37.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  9x -3:37 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:36.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:33.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  8x -3:25.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -3:16.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:15.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:15 julia-client:toggle-console (atom-text-editor.editor.vim-mode.normal-mode)
     -3:09.5.0 console:evaluate (atom-text-editor.editor.is-focused)
     -3:09.5.0 julia-client:start-julia (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -3:01.2.0 console:evaluate (atom-text-editor.editor.is-focused)
     -2:50.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 10x -2:49.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50.1.0 window:toggle-dev-tools (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "julia-client": {
    "juliaPath": "/usr/local/bin/julia4"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.13
autocomplete-bibtex, v0.6.1
autocomplete-clang, v0.8.7
autocomplete-julia, v0.1.0
build-tools, v3.7.0
ink, v0.1.1
json-schema, v0.1.13
julia-client, v0.1.2
language-cmake, v0.1.4
language-julia, v0.4.1
language-latex, v0.6.1
latex-completions, v0.3.0
linter, v1.5.0
markdown-preview-katex, v0.3.4
markdown-scroll-sync, v0.4.2
minimap, v4.13.2
pdf-view, v0.23.0
vim-mode, v0.59.0
vim-surround, v0.8.0
wordcount, v2.3.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by Varanas** [comment]
This is fixed, right?

**Comment by nilshg** [comment]
I think I saw this today on one of my machines, but after updating all packages it disappeared, so I'd tentatively say fixed.

**Comment by ssfrr** [comment]
The reproducible trigger event was fixed by JunoLab/Atom.jl#5. I suspect that there still may be some brittleness in this handling but I think it's safe to close the issue unless it rears its head again.

**Comment by ufechner7** [comment]
I have this error the first time, I use the Julia console.

**Comment by ufechner7** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.5.9


### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///opt/atom/resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2Fhome%2Fufechner%2F00PythonSoftware%2FFastSim%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Fufechner%2F00PythonSoftware%2FFastSim%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2Fopt%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2Fopt%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22PATH%22%3A%22%2Fopt%2Ftexbin%3A%2Fusr%2Flocal%2Fsbin%3A%2Fusr%2Flocal%2Fbin%3A%2Fusr%2Fsbin%3A%2Fusr%2Fbin%3A%2Fsbin%3A%2Fbin%3A%2Fusr%2Fgames%3A%2Fusr%2Flocal%2Fgames%3A%2Fsnap%2Fbin%22%2C%22INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH%22%3A%2210%22%2C%22LC_PAPER%22%3A%22de_DE.UTF-8%22%2C%22XDG_VTNR%22%3A%227%22%2C%22LC_ADDRESS%22%3A%22de_DE.UTF-8%22%2C%22XDG_SESSION_ID%22%3A%22c2%22%2C%22CLUTTER_IM_MODULE%22%3A%22xim%22%2C%22LC_MONETARY%22%3A%22de_DE.UTF-8%22%2C%22XDG_GREETER_DATA_DIR%22%3A%22%2Fvar%2Flib%2Flightdm-data%2Fufechner%22%2C%22INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE%22%3A%220%22%2C%22INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH%22%3A%2225%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22QT_LINUX_ACCESSIBILITY_ALWAYS_ON%22%3A%221%22%2C%22LC_NUMERIC%22%3A%22de_DE.UTF-8%22%2C%22GTK_MODULES%22%3A%22gail%3Aatk-bridge%3Aunity-gtk-module%22%2C%22INFINALITY_FT_CONTRAST%22%3A%220%22%2C%22INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH%22%3A%220%22%2C%22USER%22%3A%22ufechner%22%2C%22QT_ACCESSIBILITY%22%3A%221%22%2C%22LC_TELEPHONE%22%3A%22de_DE.UTF-8%22%2C%22XDG_SESSION_PATH%22%3A%22%2Forg%2Ffreedesktop%2FDisplayManager%2FSession0%22%2C%22XDG_SEAT_PATH%22%3A%22%2Forg%2Ffreedesktop%2FDisplayManager%2FSeat0%22%2C%22INFINALITY_FT_FRINGE_FILTER_STRENGTH%22%3A%220%22%2C%22DEFAULTS_PATH%22%3A%22%2Fusr%2Fshare%2Fgconf%2Fubuntu.default.path%22%2C%22INFINALITY_FT_BRIGHTNESS%22%3A%220%22%2C%22INFINALITY_FT_USE_VARIOUS_TWEAKS%22%3A%22true%22%2C%22U1404%22%3A%221%22%2C%22XDG_CONFIG_DIRS%22%3A%22%2Fetc%2Fxdg%2Fxdg-ubuntu%3A%2Fusr%2Fshare%2Fupstart%2Fxdg%3A%2Fetc%2Fxdg%22%2C%22INFINALITY_FT_GAMMA_CORRECTION%22%3A%220%20100%22%2C%22DESKTOP_SESSION%22%3A%22ubuntu%22%2C%22QT_IM_MODULE%22%3A%22ibus%22%2C%22QT_QPA_PLATFORMTHEME%22%3A%22appmenu-qt5%22%2C%22LC_IDENTIFICATION%22%3A%22de_DE.UTF-8%22%2C%22PWD%22%3A%22%2Fhome%2Fufechner%22%2C%22XDG_SESSION_TYPE%22%3A%22x11%22%2C%22XMODIFIERS%22%3A%22%40im%3Dibus%22%2C%22INFINALITY_FT_FILTER_PARAMS%22%3A%2211%2022%2038%2022%2011%22%2C%22LANG%22%3A%22en_GB.UTF-8%22%2C%22MANDATORY_PATH%22%3A%22%2Fusr%2Fshare%2Fgconf%2Fubuntu.mandatory.path%22%2C%22INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS%22%3A%22true%22%2C%22INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE%22%3A%2240%22%2C%22GDM_LANG%22%3A%22en_GB%22%2C%22INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH%22%3A%2210%22%2C%22LC_MEASUREMENT%22%3A%22de_DE.UTF-8%22%2C%22IM_CONFIG_PHASE%22%3A%221%22%2C%22COMPIZ_CONFIG_PROFILE%22%3A%22ubuntu%22%2C%22INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH%22%3A%220%22%2C%22INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT%22%3A%22100%22%2C%22INFINALITY_FT_STEM_ALIGNMENT_STRENGTH%22%3A%2225%22%2C%22PAPERSIZE%22%3A%22a4%22%2C%22GDMSESSION%22%3A%22ubuntu%22%2C%22SESSIONTYPE%22%3A%22gnome-session%22%2C%22GTK2_MODULES%22%3A%22overlay-scrollbar%22%2C%22SHLVL%22%3A%220%22%2C%22XDG_SEAT%22%3A%22seat0%22%2C%22HOME%22%3A%22%2Fhome%2Fufechner%22%2C%22LANGUAGE%22%3A%22en_GB%3Aen%22%2C%22INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE%22%3A%220%22%2C%22INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE%22%3A%220%22%2C%22XDG_SESSION_DESKTOP%22%3A%22ubuntu%22%2C%22LOGNAME%22%3A%22ufechner%22%2C%22QT4_IM_MODULE%22%3A%22xim%22%2C%22XDG_DATA_DIRS%22%3A%22%2Fusr%2Fshare%2Fubuntu%3A%2Fusr%2Fshare%2Fgnome%3A%2Fhome%2Fufechner%2F.local%2Fshare%2Fflatpak%2Fexports%2Fshare%3A%2Fvar%2Flib%2Fflatpak%2Fexports%2Fshare%2F%3A%2Fusr%2Flocal%2Fshare%2F%3A%2Fusr%2Fshare%2F%3A%2Fvar%2Flib%2Fsnapd%2Fdesktop%22%2C%22INFINALITY_FT_STEM_FITTING_STRENGTH%22%3A%2225%22%2C%22INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS%22%3A%22true%22%2C%22INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE%22%3A%220%22%2C%22XDG_RUNTIME_DIR%22%3A%22%2Frun%2Fuser%2F1000%22%2C%22DISPLAY%22%3A%22%3A0%22%2C%22GTK_IM_MODULE%22%3A%22ibus%22%2C%22XDG_CURRENT_DESKTOP%22%3A%22Unity%22%2C%22LC_TIME%22%3A%22de_DE.UTF-8%22%2C%22XAUTHORITY%22%3A%22%2Fhome%2Fufechner%2F.Xauthority%22%2C%22LC_NAME%22%3A%22de_DE.UTF-8%22%2C%22DBUS_SESSION_BUS_ADDRESS%22%3A%22unix%3Aabstract%3D%2Ftmp%2Fdbus-0WQ2PBFMQv%22%2C%22GNOME_KEYRING_CONTROL%22%3A%22%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Frun%2Fuser%2F1000%2Fkeyring%2Fssh%22%2C%22GNOME_KEYRING_PID%22%3A%22%22%2C%22GPG_AGENT_INFO%22%3A%22%2Fhome%2Fufechner%2F.gnupg%2FS.gpg-agent%3A0%3A1%22%2C%22GNOME_DESKTOP_SESSION_ID%22%3A%22this-is-deprecated%22%2C%22SESSION%22%3A%22ubuntu%22%2C%22JOB%22%3A%22unity-settings-daemon%22%2C%22INSTANCE%22%3A%22%22%2C%22UPSTART_EVENTS%22%3A%22xsession%20started%22%2C%22UPSTART_JOB%22%3A%22unity7%22%2C%22UPSTART_INSTANCE%22%3A%22%22%2C%22UPSTART_SESSION%22%3A%22unix%3Aabstract%3D%2Fcom%2Fubuntu%2Fupstart-session%2F1000%2F2121%22%2C%22COMPIZ_BIN_PATH%22%3A%22%2Fusr%2Fbin%2F%22%2C%22GIO_LAUNCHED_DESKTOP_FILE%22%3A%22%2Fusr%2Fshare%2Fapplications%2Fatom.desktop%22%2C%22GIO_LAUNCHED_DESKTOP_FILE_PID%22%3A%2219572%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22CHROME_DESKTOP%22%3A%22Atom.desktop%22%2C%22ATOM_HOME%22%3A%22%2Fhome%2Fufechner%2F.atom%22%7D%2C%22appVersion%22%3A%221.10.2%22%2C%22atomHome%22%3A%22%2Fhome%2Fufechner%2F.atom%22%2C%22shellLoadTime%22%3A534%7D:1

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/ufechner/.atom/packages/julia-client/lib/connection/ipc.coffee:94:54
    at Socket.<anonymous> (/home/ufechner/.atom/packages/julia-client/lib/misc.coffee:21:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

### Commands

```
  4x -0:02.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.3.0 console:evaluate (atom-text-editor.editor.is-focused)
     -0:00.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  },
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "juliaOptions": {
      "bootMode": "Server"
    },
    "juliaPath": "julia5",
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.5.3 (active)
julia-client, v0.5.9 (active)
language-julia, v0.8.0 (active)
latex-completions, v0.3.2 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
