### ISSUE TITLE
cannot start julia

### ISSUE THREAD

**Issue by zhangliye** [JunoLab/atom-julia-client#187]
run Julia code, then julia is not booted. The log message is as following,

Window load time: 638ms
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
Error reporting uncaught exception Error: Cannot find module '../package.json'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\exception-reporting\lib\reporter.js:14:17)
    at Object.<anonymous> (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\exception-reporting\lib\reporter.js:209:4)
    at Module._compile (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](C:UsersLiye ZhangAppDataLocalatomapp-1.8.0resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\exception-reporting\lib\main.js:19:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Liye Zhang\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:832:32
Uncaught TypeError: Cannot read property '1' of null

**Comment by pfitzseb** [comment]
How did you install Juno? Do you only get that error when `julia-client` is installed/enabled or always?

**Comment by clairvoyant** [comment]
i get it always julia executable is on the path. Nevertheless i have also tried to set the path in the julia-client configuration. 

  - Atom 1.8.0

The error is

C:\Users\jrubio\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\exception-reporting\lib\main.js:25 Error reporting uncaught exception Error: Cannot find module '../package.json'(…)(anonymous function) @ C:\Users\jrubio\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\exception-reporting\lib\main.js:25
events.js:141 Uncaught Error: spawn where ENOENT

**Comment by pfitzseb** [comment]
That's a different error -- please check that `C:\Windows\system32` is on your `Path` and add it if not.

**Comment by clairvoyant** [comment]
thank you for the answer. 

It's working now. The issue seems related to the order of the installed plugins. 
After an Atom cleanup (removed users/user/.atom,  AppLocal/atom, Roaming/Atom) and reinstaling, it works.  It works if Juno is installed as the first plugin. 

As you point out, my issue is not related to the issue described in this thread.

**Comment by zhangliye** [comment]
Thank you for you reply. I successfully installed Juno on another computer in the same way.  During installation, Juno shows no message for a longtime. I suggest to show the information during installing related packages to let users know the progress and what is happening. 

I use JuliaDT to edit the code again, because the current Julia editors are similar, only for editing the code. Another reason is that Juno does not support using Debug.jl  for debugging in in an interactive way from console window.  Hope there will be a mature IDE soon.
