### ISSUE TITLE
Uncaught TypeError: ink.Spinner is not a function

### ISSUE THREAD

**Issue by joa-quim** [JunoLab/atom-julia-client#196]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Education
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7
### Stack Trace

Uncaught TypeError: ink.Spinner is not a function

```
At /C:/Users/j/.atom/packages/julia-client/lib/julia-client.coffee:170

TypeError: ink.Spinner is not a function
    at Object.module.exports.JuliaClient.consumeInk (file:///C:/Users/j/.atom/packages/julia-client/lib/julia-client.coffee:1:1)
    at Provider.module.exports.Provider.provide (C:\Users\j\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\j\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
### Commands

```
     -3:38.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -3:34.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:34.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -1:02.6.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:20.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {},
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "juliaPath": "C:\\programs\\julia64\\usr\\bin\\julia.exe",
    "launchOnStartup": true
  }
}
```
### Installed Packages

``` coffee
# User
ink, v0.4.4
julia-client, v0.4.7
language-julia, v0.6.0
latex-completions, v0.3.1
tool-bar, v1.0.0
uber-juno, v0.1.1

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
Are you still getting that error after updating all relevant packages, @joa-quim?

**Comment by joa-quim** [comment]
No, but I now get

```
ERROR: LoadError: LoadError: LoadError: StackOverflowError:
while loading C:\j\.julia\v0.5\Blink\src\content\server.jl, in expression starting on line 18
while loading C:\j\.julia\v0.5\Blink\src\content/content.jl, in expression starting on line 46
while loading C:\j\.julia\v0.5\Blink\src\Blink.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile Blink to C:\j\.julia\lib\v0.5\Blink.ji
while loading C:\j\.julia\v0.5\Atom\src\Atom.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile Atom to C:\j\.julia\lib\v0.5\Atom.ji
 in error(::ASCIIString) at .\error.jl:21
 in compilecache(::ASCIIString) at .\loading.jl:496
 in require(::Symbol) at .\loading.jl:355
 in include(::ASCIIString) at .\boot.jl:264
 in include_from_node1(::UTF8String) at .\loading.jl:417
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\j\.atom\packages\julia-client\script\boot.jl, in expression starting on line 35
```
