### ISSUE TITLE
Uncaught TypeError: atom.workspace.isTextEditor is not a function

### ISSUE THREAD

**Issue by kkruups** [JunoLab/atom-julia-client#200]
[Enter steps to reproduce below:]

1.Install uber-juno on MacOSX 10.10.4
2.Let Uber-Juno complete installation 

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7

### Stack Trace

Uncaught TypeError: atom.workspace.isTextEditor is not a function

```
At /Users/chimi3/.atom/packages/julia-client/lib/runtime/modules.coffee:79

TypeError: atom.workspace.isTextEditor is not a function
    at Object.module.exports.updateForItem (/Users/chimi3/.atom/packages/julia-client/lib/runtime/modules.coffee:79:28)
    at /Users/chimi3/.atom/packages/julia-client/lib/runtime/modules.coffee:16:63
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:623:15)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:207:21)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:50:23)
```

### Commands

```
     -9:36.4.0 settings-view:open (atom-text-editor.editor.is-focused)
 41x -9:05.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:46.8.0 julia-client:open-console (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
 16x -4:07.5.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -4:01.5.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:54.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:47.3.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -3:40.9.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -3:37.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:34.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:26.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -3:20.2.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:50.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  },
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "launchOnStartup": true,
    "juliaPath": "/Applications/Julia-0.4.6.app/Contents/Resources/julia/bin/julia"
  }
}
```

### Installed Packages

```coffee
# User
go-plus, v3.5.2
ink, v0.4.4
julia-client, v0.4.7
language-julia, v0.6.0
latex-completions, v0.3.1
tool-bar, v1.0.0
uber-juno, v0.1.1

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
Do you still get that error after restarting Atom?

**Comment by MikeInnes** [comment]
You're on a really old version of Atom, so try updating that first.

**Comment by pfitzseb** [comment]
I'll close this for now -- if you still experience this issue after updating Atom, feel free to reopen it @kkruups.
