### ISSUE TITLE
Failed to load the julia-client package

### ISSUE THREAD

**Issue by javierpf1** [JunoLab/atom-julia-client#218]
After installing julia-client I get this error:

Failed to load the julia-client package

I'm using atom 1.8 on gentoo and julia 0.5.0. 

Here is the Stack Trace:

```
Error: ENOENT, common/api/lib/shell.js not found in /usr/lib64/electron/resources/atom.asar
    at notFoundError (ATOM_SHELL_ASAR.js:110:13)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:435:9)
    at compileFileAtPath (/usr/lib64/atom/app.asar/src/compile-cache.js:69:23)
    at Object.defineProperty.value [as .js] (/usr/lib64/atom/app.asar/src/compile-cache.js:207:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/javier/.atom/packages/julia-client/lib/package/commands.coffee:1:25)
    at Object.<anonymous> (/home/javier/.atom/packages/julia-client/lib/package/commands.coffee:1:1)
    at Module._compile (/usr/lib64/atom/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/lib64/atom/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/javier/.atom/packages/julia-client/lib/julia-client.coffee:1:12)
    at Object.<anonymous> (/home/javier/.atom/packages/julia-client/lib/julia-client.coffee:1:1)
    at Module._compile (/usr/lib64/atom/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/lib64/atom/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/lib64/atom/app.asar/src/package.js:715:27)
    at /usr/lib64/atom/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/lib64/atom/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/lib64/atom/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/lib64/atom/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib64/atom/app.asar/src/package-manager.js:536:30)
    at /usr/lib64/atom/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/lib64/atom/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/lib64/atom/app.asar/src/buffered-process.js:215:47)
    at /usr/lib64/atom/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/lib64/atom/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by pfitzseb** [comment]
I would guess this happens because gentoo distributes Atom with a newer version if Electron than atom.io (and we're not up to date with the newest Electron API). Can you try this again with a binary from there?

**Comment by javierpf1** [comment]
Sure, which version could work?

Thank you.

**Comment by javierpf1** [comment]
I tried a binary (version 1.9.9) and it worked.

Thanks for your help.

**Comment by pfitzseb** [comment]
Great!

We're working on making Juno compatible with newer versions of Electron, so hopefully that shouldn't be an issue in the future.

**Comment by pfitzseb** [comment]
What binary?
