### ISSUE TITLE
Uncaught TypeError: _this.mainModule[methodName] is not a function

### ISSUE THREAD

**Issue by JadisInteractive** [JunoLab/atom-julia-client#219]
Was installing this package for the first time when this occurred.

1. Updated Atom from 1.8 to 1.9.9
2. Followed instructions [here](https://github.com/JunoLab/uber-juno/blob/master/setup.md).
3. Of note, a couple of packages gave the same error. They were **pigments** and **remote-edit**.

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.5.0

### Stack Trace

Uncaught TypeError: _this.mainModule[methodName] is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:465

TypeError: _this.mainModule[methodName] is not a function
    at Object.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:465:50)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:113:34)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at Object.module.exports.create (/Users/jarvisaddison/.atom/packages/julia-client/lib/runtime/console.coffee:50:16)
    at Object.module.exports.activate (/Users/jarvisaddison/.atom/packages/julia-client/lib/runtime/console.coffee:15:6)
    at Object.module.exports.consumeInk (/Users/jarvisaddison/.atom/packages/julia-client/lib/runtime.coffee:24:11)
    at Object.module.exports.JuliaClient.consumeInk (/Users/jarvisaddison/.atom/packages/julia-client/lib/julia-client.coffee:33:7)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:00.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "metrics",
      "linter-jshint",
      "pigments",
      "remote-edit"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "juliaPath": "/Applications/Julia-0.4.1.app/Contents/Resources/julia/bin/julia",
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.11 (inactive)
autoclose-html, v0.23.0 (active)
color-picker, v2.2.2 (active)
dash, v1.6.2 (inactive)
file-icons, v1.7.19 (active)
ink, v0.5.0 (active)
julia-client, v0.5.0 (inactive)
language-julia, v0.6.0 (active)
latex-completions, v0.3.1 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-jshint, v2.1.0 (inactive)
linter-php, v1.2.0 (active)
markdown-preview-plus, v2.4.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
pigments, v0.34.0 (inactive)
remote-edit, v1.8.24 (inactive)
remote-sync, v4.1.2 (active)
rest-client, v1.2.2 (active)
sass-autocompile, v0.13.0 (active)
seti-syntax, v1.0.1 (active)
seti-ui, v1.3.2 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
Could you reproduce this? Kinda seems like an Atom error, so it might've already been resolved in 1.10?

**Comment by JadisInteractive** [comment]
Forgive me for not closing the issue. An update did resolve the error.

**Comment by pfitzseb** [comment]
No worries, glad it's working now!
