### ISSUE TITLE
Ubuntu 14.04 (Elementary.io) Cannot find module 'electron'

### ISSUE THREAD

**Issue by windweller** [JunoLab/atom-julia-client#269]
I tried to install actual electron using home-brew and succeeded, and I reinstalled Julia-client pacakge yet this still happens. Maybe because I didn't put electron in the path?

**Atom Version**: 1.6.0
**System**: elementary OS
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.5.9

### Stack Trace

Failed to load the julia-client package

```
At Cannot find module 'electron'

Error: Cannot find module 'electron'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/allen/.atom/packages/julia-client/lib/runtime/evaluation.coffee:2:27)
    at Object.<anonymous> (/home/allen/.atom/packages/julia-client/lib/runtime/evaluation.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/allen/.atom/packages/julia-client/lib/runtime/completions.coffee:8:14)
    at Object.<anonymous> (/home/allen/.atom/packages/julia-client/lib/runtime/completions.coffee:4:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/allen/.atom/packages/julia-client/lib/runtime.coffee:2:16)
    at Object.<anonymous> (/home/allen/.atom/packages/julia-client/lib/runtime.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/allen/.atom/packages/julia-client/lib/julia-client.coffee:9:15)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.16
autocomplete-python, v1.8.6
ink, v0.5.3
julia-client, v0.5.9
language-julia, v0.8.0
latex-completions, v0.3.2
python-indent, v1.0.0
tool-bar, v1.0.1
uber-juno, v0.1.1

# Dev
No dev packages
```

**Comment by MikeInnes** [comment]
I think your Atom version is just really old, try downloading the latest from atom.io.

**Comment by windweller** [comment]
I'll download the new version of Atom. I thought it kept it up to date.
