### ISSUE TITLE
Server mode broken on 0.5.11

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/atom-julia-client#296]
Attempting to evaluate anything (such as `1+1`) using server mode on 0.5.11 gives no results in the Julia `Console`, and in the Developer tools console, I see the following errors:

```
"/Users/sabae/.atom/packages/julia-client/lib/misc/cells.js:38
export function get (ed) {
^^^^^^
SyntaxError: Unexpected token export
  at Object.exports.runInThisContext (vm.js:76:16)
  at Module._compile (module.js:528:28)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (/Users/sabae/.atom/packages/julia-client/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/sabae/.atom/packages/julia-client/lib/misc.coffee:7:12)
  at Object.<anonymous> (/Users/sabae/.atom/packages/julia-client/lib/misc.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/Users/sabae/.atom/packages/julia-client/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/sabae/.atom/packages/julia-client/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/sabae/.atom/packages/julia-client/lib/connection/process/server.coffee:7:15)
  at Object.<anonymous> (/Users/sabae/.atom/packages/julia-client/lib/connection/process/server.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/Users/sabae/.atom/packages/julia-client/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/sabae/.atom/packages/julia-client/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/sabae/.atom/packages/julia-client/lib/connection/process/boot.js:20:16)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:402:7)
  at startup (bootstrap_node.js:157:9)
  at bootstrap_node.js:521:3
"
```

**Comment by MikeInnes** [comment]
This has fallen by the wayside a bit because even when it was working it had some racey hangs and stuff. Is cycler mode sufficient for you or do you particularly need server? It should be straightforward to fix this up anyway.

**Comment by staticfloat** [comment]
Cycler mode works, this isn't a big deal, just wanted to make certain it was known.

**Comment by MikeInnes** [comment]
Makes sense – thanks for the report!

**Comment by pfitzseb** [comment]
I've disabled the server mode setting on master -- the issue here is that the ES6 preprocessing doesn't happen when we load without going throught the Atom package chain.
