### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by Kazu-zamasu** [JunoLab/atom-julia-client#307]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.5.11

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /home/kazu/.atom/packages/julia-client/lib/connection.coffee:30

TypeError: Cannot read property 'then' of undefined
    at Object.boot (/home/kazu/.atom/packages/julia-client/lib/connection.coffee:30:50)
    at boot (/home/kazu/.atom/packages/julia-client/lib/package/commands.coffee:9:31)
    at /home/kazu/.atom/packages/julia-client/lib/package/commands.coffee:75:72
    at Object.disrequire (/home/kazu/.atom/packages/julia-client/lib/connection/client.coffee:148:27)
    at disrequireClient (/home/kazu/.atom/packages/julia-client/lib/package/commands.coffee:8:57)
    at atom-workspace.julia-client:start-julia (/home/kazu/.atom/packages/julia-client/lib/package/commands.coffee:75:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1175:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:319:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:46 settings-view:open (atom-pane.pane.active)
     -2:23.1.0 core:paste (input.hidden-input)
     -2:21.8.0 core:confirm (input.hidden-input)
     -0:11.4.0 core:paste (input.hidden-input)
     -0:00.2.0 julia-client:start-julia (input.hidden-input)
```

### Config

```json
{
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.6.2 (active)
julia-client, v0.5.11 (active)
language-julia, v0.10.0 (active)
latex-completions, v0.3.2 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
This shouldn't be a problem anymore on the latest version (please reopen this issue if it still is).

**Comment by xhipster** [comment]
<img width="481" alt="screenshot 2019-01-17 at 04 19 53" src="https://user-images.githubusercontent.com/410789/51291277-3b1b7e80-1a0f-11e9-9e94-24840c92f47c.png">

```
TypeError: Cannot read property 'then' of undefined
    at Object._boot (/Users/xhipster/.atom/packages/julia-client/lib/connection.coffee:49:50)
    at Object.boot (/Users/xhipster/.atom/packages/julia-client/lib/connection.coffee:56:6)
    at boot (/Users/xhipster/.atom/packages/julia-client/lib/package/commands.coffee:9:31)
    at /Users/xhipster/.atom/packages/julia-client/lib/package/commands.coffee:80:72
    at Object.disrequire (/Users/xhipster/.atom/packages/julia-client/lib/connection/client.coffee:197:27)
    at disrequireClient (/Users/xhipster/.atom/packages/julia-client/lib/package/commands.coffee:8:57)
    at HTMLElement.julia-client:start-julia (/Users/xhipster/.atom/packages/julia-client/lib/package/commands.coffee:80:38)
    at CommandRegistry.handleCommandEvent (/Users/xhipster/apps/atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (/Users/xhipster/apps/atom.app/Contents/Resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Users/xhipster/apps/atom.app/Contents/Resources/app/static/<embedded>:1:669184)
    at EventEmitter.t (/Users/xhipster/apps/atom.app/Contents/Resources/app/static/<embedded>:1:676568)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

Atom 1.34

**Comment by pfitzseb** [comment]
What version of julia-client and ink are you running?
