### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toggle' of undefined

### ISSUE THREAD

**Issue by SergeUK** [JunoLab/atom-julia-client#36]
I just installed Atom and followed the instructions on https://github.com/JunoLab/atom-julia-client/tree/master/manual. I have julia v0.4.0-rc2 running on my Windows 10. 

The error message is "Uncaught TypeError: Cannot read property 'toggle' of undefined" when I run the Julia Client: Toggle Console command from Atom.

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Home
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'toggle' of undefined

```
At /C:/Users/Serge/.atom/packages/julia-client/lib/ui/console.coffee:71

TypeError: Cannot read property 'toggle' of undefined
  at Object.module.exports.toggle (C:\Users\Serge\.atom\packages\julia-client\lib\ui\console.coffee:36:16)
  at C:\Users\Serge\.atom\packages\julia-client\lib\julia-client.coffee:83:58
  at Object.module.exports.JuliaClient.withInk (C:\Users\Serge\.atom\packages\julia-client\lib\julia-client.coffee:106:7)
  at atom-workspace.subs.add.atom.commands.add.julia-client:toggle-console (C:\Users\Serge\.atom\packages\julia-client\lib\julia-client.coffee:83:42)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Serge\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Serge\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Serge\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Serge\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-li.<anonymous> (C:\Users\Serge\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\Users\Serge\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (C:\Users\Serge\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -1:12.7.0 core:delete (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
  3x -1:03.9.0 core:backspace (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
     -1:01.1.0 editor:consolidate-selections (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
     -1:01.1.0 core:cancel (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
     -0:52.1.0 command-palette:toggle (atom-text-editor#julia-client.juliaArguments.editor.mini.is-focused)
  9x -0:49.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:43.9.0 julia-client:toggle-console (atom-text-editor#julia-client.juliaArguments.editor.mini)
     -0:12.3.0 command-palette:toggle (div.settings-view.pane-item)
  5x -0:09.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 julia-client:toggle-console (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\\\Users\\Serge"
  },
  "julia-client": {
    "juliaPath": "C:\\\\Users\\\\Serge\\\\AppData\\\\Local\\\\Julia-0.4.0-rc2\\\\bin\\\\julia.exe"
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.1.1
julia-client, v0.1.2
language-julia, v0.4.1

# Dev
No dev packages
```

**Comment by dysonance** [comment]
I got this error too after doing all the installs and trying to run the REPL, but everything worked great after restarting Atom. As basic as it sounds, I figured I'd bring it up because I'll be the first to admit it's easy to forget restarting things after making changes the computer needs to digest before working properly.

**Comment by Varanas** [comment]
I think I've seen this before, but can't reproduce it. Tentatively labeling as bug.

**Comment by Varanas** [comment]
Has anyone seen something like this lately?
I'm think I haven't had this error for some time, but am not totally sure.

**Comment by spencerlyon2** [comment]
Also haven't seen it for a while. I vote we close for now and re-open if (when) necessary

**Comment by Varanas** [comment]
Agreed.
