### ISSUE TITLE
Uncaught TypeError: _this.errorLines.lights.destroy is not a function

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#38]
I think this happens when trying to eval some code after an error. Maybe has to do with the new error highlighting functionality?

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.1.2

### Stack Trace

Uncaught TypeError: _this.errorLines.lights.destroy is not a function

```
At /Users/srussell/local/src/julia-client/lib/eval.coffee:55

TypeError: _this.errorLines.lights.destroy is not a function
  at Object.destroy (/Users/srussell/local/src/julia-client/lib/eval.coffee:55:28)
  at Object.module.exports.removeLines (/Users/srussell/local/src/ink/lib/editor/results.coffee:127:9)
  at Object.module.exports.show (/Users/srussell/local/src/ink/lib/editor/results.coffee:46:13)
  at Object.module.exports.showForRange (/Users/srussell/local/src/ink/lib/editor/results.coffee:71:15)
  at Object.module.exports.showForLines (/Users/srussell/local/src/ink/lib/editor/results.coffee:76:6)
  at Object.<anonymous> (/Users/srussell/local/src/julia-client/lib/eval.coffee:31:18)
  at Object.module.exports.input (/Users/srussell/local/src/julia-client/lib/connection/client.coffee:21:9)
  at /Users/srussell/local/src/julia-client/lib/connection/tcp.coffee:36:16
  at Socket.<anonymous> (/Users/srussell/local/src/julia-client/lib/connection/tcp.coffee:17:9)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:520:20)

```

### Commands

```
     -0:40.2.0 julia-client:toggle-console (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  3x -0:31.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:30.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:30.6.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:30.3.0 julia-client:evaluate (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:28.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:28 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:25 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:24.5.0 julia-client:evaluate (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  5x -0:16.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:15.2.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:14.8.0 julia-client:evaluate (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:09.3.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  5x -0:08.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.6.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.3.0 julia-client:evaluate (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "julia-client": {
    "juliaPath": "/usr/local/bin/julia4",
    "juliaArguments": "-q --depwarn=error"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.13
autocomplete-bibtex, v0.6.1
autocomplete-clang, v0.8.7
build-tools, v3.7.0
ink, v0.1.1
json-schema, v0.1.13
julia-client, v0.1.2
language-cmake, v0.1.4
language-julia, v0.4.1
language-latex, v0.6.1
latex-completions, v0.3.0
lcov-info, v0.10.4
linter, v1.5.1
markdown-preview-katex, v0.3.4
markdown-scroll-sync, v0.4.2
minimap, v4.13.3
pdf-view, v0.23.0
vim-mode, v0.60.0
vim-surround, v0.8.0
wordcount, v2.3.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by ssfrr** [comment]
Oh I didn't have the latest Ink. I'll check but I'm guessing that'll fix it.

**Comment by ssfrr** [comment]
yep. sorry for the noise.
