### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by KristofferC** [JunoLab/atom-julia-client#412]
Execute "Reset Julia Julia Server"

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.6.7

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of undefined

```
At /Users/kristoffer/.atom/packages/julia-client/lib/package/commands.coffee:83

TypeError: Cannot read property 'reset' of undefined
    at /packages/julia-client/lib/package/commands.coffee:83:73)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:06.7.0 julia-client:run-and-move (input.hidden-input)
     -1:20.7.0 julia-client:kill-julia (input.hidden-input)
     -1:16.6.0 julia-client:interrupt-julia (textarea.xterm-helper-textarea)
     -1:11.3.0 core:copy (input.hidden-input)
     -1:10.3.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -0:59.8.0 ink-terminal:copy (textarea.xterm-helper-textarea)
 28x -0:58.5.0 julia-client:interrupt-julia (textarea.xterm-helper-textarea)
     -0:37.4.0 command-palette:toggle (textarea.xterm-helper-textarea)
  2x -0:35.3.0 core:move-down (input.hidden-input)
     -0:34.8.0 core:confirm (input.hidden-input)
     -0:34.8.0 julia-client:new-terminal (textarea.xterm-helper-textarea)
     -0:13.9.0 command-palette:toggle (input.hidden-input)
     -0:11.7.0 core:select-all (input.hidden-input)
     -0:09.8.0 core:move-down (input.hidden-input)
     -0:09.1.0 core:confirm (input.hidden-input)
     -0:09.1.0 julia-client:reset-julia-server (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.2.0 
ink 0.8.1 
julia-client 0.6.7 
language-julia 0.15.0 
latex-completions 0.3.3 
tool-bar 1.1.4 
uber-juno 0.1.2 
```

**Comment by pfitzseb** [comment]
Thanks. This command doesn't do anything since server mode is disabled, so I've removed it: https://github.com/JunoLab/atom-julia-client/commit/a0a693f79014f0df752e840c94df767747b91e02
