### ISSUE TITLE
problem installing the newest version julia-client v0.6.7

### ISSUE THREAD

**Issue by rchen14** [JunoLab/atom-julia-client#415]
Hi, I had the following trouble when adding juno package to atom editor. Have been using juno for more than half year, this issue happened during the last julia-client package update. uber-juno, julia-language can still be installed successfully, but it returns the following error message every time installing or updating julia-client:

```
> node-pty-prebuilt@0.7.3 install C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr\node_modules\julia-client\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr\node_modules\julia-client\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\richard\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\richard\AppData\Local\atom\app-1.23.3\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr
`-- (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr\node_modules\julia-client\node_modules\prebuild-install\bin.js:19
if (rc.path) process.chdir(rc.path)
                     ^

Error: EPERM: operation not permitted, uv_chdir
    at Error (native)
    at Object.<anonymous> (C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr\node_modules\julia-client\node_modules\prebuild-install\bin.js:19:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\richard\AppData\Local\Enthought\Canopy\edm\envs\User\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\richard\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\richard\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\richard\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\richard\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr\package.json'
npm WARN apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr No description
npm WARN apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr No repository field.
npm WARN apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr No README data
npm WARN apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\richard\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\richard\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\richard\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\richard\\.atom\\.apmrc" "install" "C:\\Users\\richard\\AppData\\Local\\Temp\\d-118028-13276-x8qmdg.c1acjqyqfr\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style" "--msvs_version=2013"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty-prebuilt@0.7.3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.3 install script 'prebuild-install || node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\richard\AppData\Local\Temp\apm-install-dir-118028-13276-hxoyaa.w9mhzadcxr\npm-debug.log
npm ERR! code 1
```

**Comment by pfitzseb** [comment]
This seems to be a permission issue -- did you install Atom with the same User you're using now? Do you have a separate node installation (6.9.5 is older than the 7.4.0 shipped with my install of Atom 1.23)? 

You might want to try renaming `C:\Users\richard\.atom` to `C:\Users\richard\.atom.bak` and reinstall Juno from scratch; if that doesn't work then also try reinstalling Atom.

**Comment by rchen14** [comment]
Yes. It is a permission issue. Now it is resolved. Thanks!

**Comment by xanfus** [comment]
apm install julia-client
`Error: EPERM: operation not permitted, open 'C:\Users\acer\.atom\packages\julia-client\script\spawnInterruptible.ps1'       at Error (native) `

**Comment by brunnooliver7** [comment]
How did you solve it? I'm having the same problem

**Comment by xanfus** [comment]
Had i ran "Atom" as admin to perform package installation?

**Comment by rchen14** [comment]
@brunnooliver7 you can try to start atom as admin - do not have to change the security settings of relevant folders.
