### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setItems' of undefined

### ISSUE THREAD

**Issue by jjdegruijter** [JunoLab/atom-julia-client#428]
[Enter steps to reproduce:]

1. Restart Atom to link it with newly installed Julia v. 0.6.2
2. From Atom try to run a Julia script developed with Julia v. 0.5

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.10.5
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.6.8

### Stack Trace

Uncaught TypeError: Cannot read property 'setItems' of undefined

```
At /Users/jjdegruijter/.atom/packages/julia-client/lib/runtime/workspace.coffee:21

TypeError: Cannot read property 'setItems' of undefined
    at Object.update (/packages/julia-client/lib/runtime/workspace.coffee:21:15)
    at debugmode (/packages/julia-client/lib/runtime/debugger.js:45:15)
    at /packages/julia-client/lib/runtime/debugger.js:19:5
    at Function.module.exports.Emitter.simpleDispatch (/Users/jjdegruijter/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/jjdegruijter/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Object.detach (/packages/julia-client/lib/connection/client.coffee:85:14)
    at /packages/julia-client/lib/connection/local.coffee:70:30)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
ink 0.6.1 
julia-client 0.6.8 
language-julia 0.10.0 
latex-completions 0.3.2 
tool-bar 1.0.1 
uber-juno 0.1.1 
```

**Comment by pfitzseb** [comment]
Do you have an `@enter` somewhere in there?

**Comment by jjdegruijter** [comment]
No, I don't

**Comment by pfitzseb** [comment]
You're running a massively outdated version of `ink` -- please update to the [v0.8.2](https://github.com/JunoLab/atom-ink/releases/tag/v0.8.2).

**Comment by jjdegruijter** [comment]
Thanks.
I’ve downloaded it, but don’t know how to install it properly.

**Comment by pfitzseb** [comment]
Atom should prompt you to update all outdated packages:
![grafik](https://user-images.githubusercontent.com/6735977/36676257-76c9844e-1b0b-11e8-89d6-b7c55c59c1ef.png)
There should be no need to update anything manually.
