### ISSUE TITLE
Julia client not installing on ATOM

### ISSUE THREAD

**Issue by farhangithub27** [JunoLab/atom-julia-client#440]
Installing “julia-client@0.6.10” failed.Hide output…

> node-pty-prebuilt@0.7.3 install C:\Users\Farhan\AppData\Local\Temp\apm-install-dir-118213-9800-kqeey8.30cxlayvi\node_modules\julia-client\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js

C:\Users\Farhan\AppData\Local\Temp\apm-install-dir-118213-9800-kqeey8.30cxlayvi\node_modules\julia-client\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Farhan\AppData\Local\atom\app-1.24.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Farhan\AppData\Local\atom\app-1.24.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\Farhan\AppData\Local\Temp\apm-install-dir-118213-9800-kqeey8.30cxlayvi
`-- (empty)

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\node-pty-prebuilt-v0.7.3-electron-v53-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Farhan\.atom\.apm\_prebuilds\https-github.com-daviwil-node-pty-prebuilt-releases-download-v0.7.3-node-pty-prebuilt-v0.7.3-electron-v53-win32-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ C:\Users\Farhan\.atom\.apm\_prebuilds\https-github.com-daviwil-node-pty-prebuilt-releases-download-v0.7.3-node-pty-prebuilt-v0.7.3-electron-v53-win32-x64.tar.gz
prebuild-install WARN install unexpected end of file
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Anaconda3\python.EXE" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Farhan\AppData\Local\atom\app-1.24.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Farhan\AppData\Local\atom\app-1.24.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Farhan\\AppData\\Local\\atom\\app-1.24.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Farhan\\AppData\\Local\\atom\\app-1.24.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Farhan\AppData\Local\Temp\apm-install-dir-118213-9800-kqeey8.30cxlayvi\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Farhan\AppData\Local\Temp\apm-install-dir-118213-9800-kqeey8.30cxlayvi\package.json'
npm WARN apm-install-dir-118213-9800-kqeey8.30cxlayvi No description
npm WARN apm-install-dir-118213-9800-kqeey8.30cxlayvi No repository field.
npm WARN apm-install-dir-118213-9800-kqeey8.30cxlayvi No README data
npm WARN apm-install-dir-118213-9800-kqeey8.30cxlayvi No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\Farhan\\AppData\\Local\\atom\\app-1.24.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Farhan\\AppData\\Local\\atom\\app-1.24.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Farhan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Farhan\\.atom\\.apmrc" "install" "C:\\Users\\Farhan\\AppData\\Local\\Temp\\d-118213-9800-4sbl9p.6aekjiqkt9\\package.tgz" "--runtime=electron" "--target=1.6.16" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty-prebuilt@0.7.3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.3 install script 'prebuild-install || node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Farhan\AppData\Local\Temp\apm-install-dir-118213-9800-kqeey8.30cxlayvi\npm-debug.log
npm ERR! code 1

**Comment by pfitzseb** [comment]
I think something went wrong when downloading some dependencies. Should be able to just try again I think.

**Comment by farhangithub27** [comment]
I have tried many times on different days but its working out.

**Comment by pfitzseb** [comment]
Can you try to manually download [this file](https://github.com/daviwil/node-pty-prebuilt/releases/download/v0.7.3/node-pty-prebuilt-v0.7.3-electron-v53-win32-x64.tar.gz) and try to unpack it? You're getting a `prebuild-install WARN install unexpected end of file` in the log above, so I suspect the file might get corrupted somehow.

**Comment by pfitzseb** [comment]
What's weird here is that you shouldn't actually need to build anything -- `node-pty-prebuilt` has binaries you should be able to use.
You are getting `prebuild-install WARN install ENAMETOOLONG: name too long, open ‘/home/niels/.atom/.apm/_prebuilds/https-github.com-daviwil-node-pty-prebuilt-releases-download-v0.7.3-node-pty-prebuilt-v0.7.3-electron-v54-linux-x64.tar.gz.27915-536d93bd3018e.tmp’` after downloading the correct (from what I can tell) binary.

**Comment by nwschurink** [comment]
Sorry for not replying, I am not sure though if you need any extra info. I did see the warning for the too long file name. However, performing the 'dirty fix' mentioned above (i.e. directly pointing the python-interceptor to the python 2.7 interpreter instead of my default python v3.6) seems to work eventhough I expect the temporary file name to be the same (length). Perhaps adding a version check in the python interceptor and checking for a python2 install resolves the bug right?

**Comment by pfitzseb** [comment]
I'm glad you got it working, but the point is that you shouldn't *need* python at all to install julia-client or it's dependencies.
I suspect that the `ENAMETOOLONG` makes `prebuild-install` fail, so it falls back to building `node-pty`.

**Comment by reams** [comment]
I get a similar error message and I have Python 3.5.4 installed on an Ubuntu 16.04 machine -> 

Installing “julia-client@0.6.12” failed.Hide output…

> node-pty-prebuilt@0.7.3 install /tmp/apm-install-dir-118330-10163-139dtnu.fd1kedn29/node_modules/julia-client/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

/tmp/apm-install-dir-118330-10163-139dtnu.fd1kedn29
└── (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install ENAMETOOLONG: name too long, open '/home/jean-victor/.atom/.apm/_prebuilds/https-github.com-daviwil-node-pty-prebuilt-releases-download-v0.7.3-node-pty-prebuilt-v0.7.3-electron-v54-linux-x64.tar.gz.10302-1f746b13a169.tmp'
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.5.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.4.0-122-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118330-10163-139dtnu.fd1kedn29/node_modules/julia-client/node_modules/node-pty-prebuilt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118330-10163-139dtnu.fd1kedn29/package.json'
npm WARN apm-install-dir-118330-10163-139dtnu.fd1kedn29 No description
npm WARN apm-install-dir-118330-10163-139dtnu.fd1kedn29 No repository field.
npm WARN apm-install-dir-118330-10163-139dtnu.fd1kedn29 No README data
npm WARN apm-install-dir-118330-10163-139dtnu.fd1kedn29 No license field.
npm ERR! Linux 4.4.0-122-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/jean-victor/.atom/.apm/.apmrc" "--userconfig" "/home/jean-victor/.atom/.apmrc" "install" "/tmp/d-118330-10163-1naqptk.r9pwlv7vi/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty-prebuilt@0.7.3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.3 install script 'prebuild-install || node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118330-10163-139dtnu.fd1kedn29/npm-debug.log
npm ERR! code 1

I tried uninstalling julia-client and then reinstalling it with the same result, and then reinstalling Atom.
Now Atom doesn't even see Julia at all; it doesn't even show up in the menu.

**Comment by nwschurink** [comment]
Perhaps it is possible to hash the path before parsing it to npm? I see something similar suggested here: https://github.com/kulshekhar/ts-jest/pull/300 and it seems to solve the problem.

**Comment by pfitzseb** [comment]
Probably, but the weird thing is that those paths are only ~180 chars long (and the filename is like 145 chars) -- no sane filesystem should have that low a limit.
I'll ask about this upstream.

**Comment by pfitzseb** [comment]
@reams, @nwschurink Can you give some info on the OS and File System you're using?

**Comment by nwschurink** [comment]
Hmm, it's very weird indeed. The filesystem that I'm using is ext4. According to what I read online the PATH_MAX can be unlimited (but usually is 4096 bytes), and the NAME_MAX is usually 255 for ext4 systems. When I'm back home I'll check the sytem limits.h headers file to see what the limits are for my particular system. 

-- edit --
Ok, I think I have found the problem for the filename length.

During the install of linux I selected the option to encrypt my home folder. According to: 
https://askubuntu.com/questions/728465/how-can-i-increase-ubuntus-143-byte-file-name-limit-for-encrypted-directories/728525
The maximum file name length as a result of encryption is then set to 143 bytes. The remaining 112 bytes are needed for filename encryption. Using more than 143 will result in an encrypted filename that is longer than 255 and thus exceeding ext4 max file name.
This means that the filename of the prebuild binaries do indeed exceed the maximum allowed number of character on my (and @reams )

**Comment by pfitzseb** [comment]
Nice sleuthing! I'll ask upstream if we can make sure filenames are shorter than 140 bytes or something like that.

**Comment by difranco** [comment]
I am still seeing this issue on atom 1.38.2 / julia-client 0.8.10. It still seems to be pulling the old version of node-pty-prebuilt.

**Comment by johnnychen94** [comment]
FYI, if you're in a python3 environment(e.g., anaconda with python3), it will cause the same problem.

You have to make sure `python --version` is `2.7` before opening atom. My workaround is to temporarily move `$HOME/anaconda3` out from `PATH`.
