### ISSUE TITLE
Uncaught TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by LifeWorks** [JunoLab/atom-julia-client#444]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.6.10

### Stack Trace

Uncaught TypeError: Cannot read property 'close' of undefined

```
At /Users/songfeng/.atom/packages/julia-client/lib/ui/layout.js:97

TypeError: Cannot read property 'close' of undefined
    at standard (/packages/julia-client/lib/ui/layout.js:97:72)
    at NotificationElement.onDidClick (/packages/julia-client/lib/ui/layout.js:6:7)
    at HTMLAnchorElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:139:48)
```

### Commands

```
     -5:15.4.0 core:confirm (input.hidden-input)
     -2:55.2.0 core:backspace (input.hidden-input)
  2x -2:54.9.0 core:confirm (input.hidden-input)
     -1:06.0 core:backspace (input.hidden-input)
     -1:03.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-solarized-dark-syntax 1.2.7 
atom-solarized-dark-ui 0.28.1 
autocomplete-java 1.2.7 
busy 0.7.0 
busy-signal 1.4.3 
ide-java 0.8.2 
ink 0.8.3 
intentions 1.1.5 
java-class-complete 0.0.6 
java-classpath-registry 0.4.0 
java-generator 2.2.3 
java-generator-plus 2.6.0 
java-import-wiz 0.5.0 
java-importer 1.4.1 
java-plus 0.1.0 
jonikorpi-atom-solarized-syntax 0.2.4 
julia-client 0.6.10 
language-julia 0.15.0 
linter 2.2.0 
linter-javac 1.9.4 
linter-ui-default 1.7.1 
monokai-solarized-dark 0.1.1 
ptx-solarized-dark-syntax 0.1.0 
solarized-dark-bold-syntax 0.4.0 
solarized-dark-ui 0.3.2 
solarized-light-dark-syntax 1.0.0 
solarized-light-js-syntax 1.1.0 
solarized-light-syntax-modified 0.6.2 
solarized-light-ui 0.1.0 
solarized-one-dark-syntax 1.1.0 
solarized-one-light-ui 1.10.10 
solarized-seti-ui 0.8.6 
textmate-solarized-dark-syntax 0.2.0 
```

**Comment by pfitzseb** [comment]
Can you give some info on what you were doing when the error occured?

**Comment by pfitzseb** [comment]
Should be fixed on the latest release.

**Comment by rantecki** [comment]
FYI - I just got this error when attempting to install the latest uber-juno package (v0.2.0) into the latest Atom release (v1.34.0) on Ubuntu 18.04.  The julia-client package is version 0.7.12.

Stack trace:

```
TypeError: Cannot read property 'close' of undefined
    at standard (/home/richard/.atom/packages/julia-client/lib/ui/layout.js:92:73)
    at NotificationElement.onDidClick (/home/richard/.atom/packages/julia-client/lib/ui/layout.js:6:7)
    at HTMLAnchorElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:11:885518)
```

In case it helps, it also shows a "Cannot read property 'fromId' of undefined" error.

Stack trace:

```
TypeError: Cannot read property 'fromId' of undefined
    at Object.activate (/home/richard/.atom/packages/julia-client/lib/runtime/console2.js:43:30)
    at Object.consumeInk (/home/richard/.atom/packages/julia-client/lib/runtime.coffee:27:15)
    at Object.consumeInk (/home/richard/.atom/packages/julia-client/lib/julia-client.coffee:43:7)
    at Provider.t.exports.Provider.provide (/usr/share/atom/resources/app/static/<embedded>:14:1034817)
    at ServiceHub.t.exports.ServiceHub.consume (/usr/share/atom/resources/app/static/<embedded>:11:2916389)
    at Package.activateServices (/usr/share/atom/resources/app/static/<embedded>:11:2924521)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:2921355)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:2920679)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:2918310)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:2920539)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:2920482)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382681)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:382297)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:332481)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:382247)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:381865)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:660921)
    at <anonymous>
```

**Comment by rantecki** [comment]
Version of ink is 0.9.14

I uninstalled Juno and reinstalled, and it looks like everything is now working.  It sounds like it might be a first-time bootstrapping issue.

**Comment by pfitzseb** [comment]
Yeah, I think that was an issue that happened when updating and not restarting or something like that.

**Comment by brenhinkeller** [comment]
Looks like some version of this is happening again 
```
TypeError: Cannot read property 'close' of undefined
    at Object.standard (/Users/username/.atom/packages/julia-client/lib/ui/layout.js:94:73)
    at HTMLElement.julia:standard-layout (/Users/username/.atom/packages/julia-client/lib/package/commands.coffee:110:50)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:677666)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:842467)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:837346)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214917)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211051)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285128)
```

Half my Atom windows are refusing to open Julia in the console after updating to Julia-client 0.8.6, throwing either this error or `Cannot set property 'scrollback' of undefined`

**Comment by pfitzseb** [comment]
Can you try the installation instructions described [here](https://discourse.julialang.org/t/ann-juno-0-8-7/24682)? Namely,
```
apm uninstall ink
apm uninstall julia-client
apm install ink
apm install julia-client
```
in a terminal.

**Comment by brenhinkeller** [comment]
Thanks, seems to mostly work now. One of my Atom windows still gave the scrollback error, but closing the window and re-opening the project fixed it.

**Comment by xiligey** [comment]
I can use it after I reinstall ink and julia-client.

**Comment by agentwyz** [comment]
Thank you!! @pfitzseb
