### ISSUE TITLE
Uncaught SyntaxError: Unexpected token [ in JSON at position 27

### ISSUE THREAD

**Issue by essenciary** [JunoLab/atom-julia-client#464]
[Enter steps to reproduce:]

I just started atom and started the Julia session in the REPL.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.6.12

### Stack Trace

Uncaught SyntaxError: Unexpected token [ in JSON at position 27

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token [ in JSON at position 27
    at JSON.parse (<anonymous>)
    at /packages/julia-client/lib/connection/ipc.coffee:96:64
    at /packages/julia-client/lib/misc.coffee:24:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -5:52 application:reopen-project (input.hidden-input)
     -5:29.6.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -5:25.1.0 application:add-project-folder (div.tool-panel.tree-view)
     -4:54.8.0 command-palette:toggle (div.tool-panel.tree-view)
  3x -4:50.8.0 core:move-down (input.hidden-input)
     -4:49.4.0 core:confirm (input.hidden-input)
     -4:49.4.0 project-manager:save-project (div.tool-panel.tree-view)
     -4:36.3.0 core:close (atom-pane.pane)
     -4:35.3.0 command-palette:toggle (input.hidden-input)
 12x -4:33.3.0 core:move-down (input.hidden-input)
 12x -4:29.1.0 core:move-up (input.hidden-input)
  2x -4:26.6.0 core:move-down (input.hidden-input)
     -4:25.1.0 core:confirm (input.hidden-input)
     -4:25.1.0 project-manager:save-project (input.hidden-input)
  4x -4:08.1.0 hey-pane:toggle-focus-of-active-pane (input.hidden-input)
     -3:56.2.0 core:confirm (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.2 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-bracket-highlight 0.3.2 
atom-ide-ui 0.11.1 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-python-run 0.9.6 
autoclose-html 0.23.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
code-peek 1.4.21 
editorconfig 2.2.2 
emmet 2.4.3 
fancy-bracket-matcher 2.1.0 
file-icons 2.1.19 
git-control 0.9.0 
git-diff-details 1.4.0 
git-plus 7.10.2 
git-status 0.3.4 
git-time-machine 1.5.9 
goto-definition 1.3.4 
hey-pane 1.1.0 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-to-css 0.2.2 
Hydrogen 2.4.1 
hyperclick 0.0.0 
hyperclick-php 0.2.1 
ide-php 0.7.14 
ide-python 0.9.2 
ink 0.8.4 
intentions 1.1.5 
jekyll 2.1.0 
jekyll-syntax-highlighting 0.1.0 
julia-client 0.6.12 
language-julia 0.16.0 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-js-yaml 1.3.0 
linter-julia 0.7.3 
linter-markdown 5.2.1 
linter-php 1.5.1 
linter-python 3.1.2 
linter-ui-default 1.7.1 
markdown-img-paste 0.3.9 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
merge-conflicts 1.4.5 
monokai-seti 0.9.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
php-debug 0.2.6 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-base 3.5.0 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
pigments 0.40.2 
pinned-tabs 2.0.5 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
project-plus 1.0.0 
python-debugger 0.2.0 
python-indent 1.1.5 
python-tools 0.6.9 
save-session 0.15.7 
seti-icons 1.5.4 
seti-syntax 1.1.3 
seti-ui 1.10.0 
sort-lines 0.18.0 
swackets 0.35.0 
sync-settings 0.8.6 
teletype 0.13.1 
toggle-markdown-task 0.6.0 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.3.1 
v-bootstrap4 0.2.2 
```

**Comment by goodguy00** [comment]
i've just installed atom 1.34.0 (default offered in dnf) for fedora29. then did as advised in platformio for atom on linux.
result (from log):
"14 error Error parsing /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json: Unexpected token # in JSON at position 0"
when i look at that file: 
"bash-4.4$ head /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json
#!/usr/bin/node
{
  "_args": [
    [
....."
well ... could this be my fault?
cheers,
Petr.

**Comment by pfitzseb** [comment]
I don't think so -- if I had to guess something went wrong while installing the package. Can you try 
```
apm uninstall julia-client
apm install julia-client
```
in a terminal?
