### ISSUE TITLE
Canno install julia-client 0.6.13

### ISSUE THREAD

**Issue by brunnooliver7** [JunoLab/atom-julia-client#472]
I tried to install julia-client 0.6.13 and it apears this error:

> node-pty-prebuilt@0.7.3 install C:\Users\Usuario\AppData\Local\Temp\apm-install-dir-118427-2140-1o5er1n.2ruhy6i529\node_modules\julia-client\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js

C:\Users\Usuario\AppData\Local\Temp\apm-install-dir-118427-2140-1o5er1n.2ruhy6i529\node_modules\julia-client\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Usuario\AppData\Local\atom\app-1.27.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Usuario\AppData\Local\atom\app-1.27.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\Usuario\AppData\Local\Temp\apm-install-dir-118427-2140-1o5er1n.2ruhy6i529
`-- (empty)

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install self signed certificate in certificate chain
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\Usuario\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Usuario\AppData\Local\atom\app-1.27.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Usuario\AppData\Local\atom\app-1.27.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Usuario\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Usuario\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Usuario\AppData\Local\Temp\apm-install-dir-118427-2140-1o5er1n.2ruhy6i529\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Usuario\AppData\Local\Temp\apm-install-dir-118427-2140-1o5er1n.2ruhy6i529\package.json'
npm WARN apm-install-dir-118427-2140-1o5er1n.2ruhy6i529 No description
npm WARN apm-install-dir-118427-2140-1o5er1n.2ruhy6i529 No repository field.
npm WARN apm-install-dir-118427-2140-1o5er1n.2ruhy6i529 No README data
npm WARN apm-install-dir-118427-2140-1o5er1n.2ruhy6i529 No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\Usuario\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Usuario\\AppData\\Local\\atom\\app-1.27.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Usuario\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Usuario\\.atom\\.apmrc" "install" "C:\\Users\\Usuario\\AppData\\Local\\Temp\\d-118427-2140-1ljzpt3.gy5uahsemi\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty-prebuilt@0.7.3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.3 install script 'prebuild-install || node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Usuario\AppData\Local\Temp\apm-install-dir-118427-2140-1o5er1n.2ruhy6i529\npm-debug.log
npm ERR! code 1

How can I solve it?

**Comment by pfitzseb** [comment]
That's weird. Can you try completly closing Atom, open a terminal and type in `apm install julia-client`? If that errors as well, please paste the output here.

**Comment by brunnooliver7** [comment]
It didn´t work.

![image](https://user-images.githubusercontent.com/39685296/40618314-82e5dd4c-6267-11e8-8d86-6e44460815cb.png)

**Comment by Noman5237** [comment]
I have run the `apm install julia-client` but it comes with the following error
```
npm ERR! addLocal Could not install C:\Users\NOMAN^~1\AppData\Local\Temp\d-11855-3752-11yo7z2.dul4sra4i\package.tgz
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\Noman^Alien#0637\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Noman^Alien#0637\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Noman^Alien#0637\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Noman^Alien#0637\\.atom\\.apmrc" "install" "C:\\Users\\NOMAN^~1\\AppData\\Local\\Temp\\d-11855-3752-11yo7z2.dul4sra4i\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\Noman^Alien\julia-client\0.6.13\package.tgz.1634265688
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Noman^Alien\julia-client\0.6.13\package.tgz.1634265688'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, open 'C:\Users\Noman^Alien\julia-client\0.6.13\package.tgz.1634265688'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Noman^Alien\\julia-client\\0.6.13\\package.tgz.1634265688' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NOMAN^~1\AppData\Local\Temp\apm-install-dir-11855-3752-1xheadq.d7xwhwu3di\npm-debug.log
```
And I cannot access the Temp folder to get the log file

**Comment by pfitzseb** [comment]
That's a permission error -- make sure the user you're trying to install julia-client on is the same that installed Atom. In particular, `Please try running this command again as root/Administrator.`.
