### ISSUE TITLE
Uncaught Error: Cannot find module '../runtime'

### ISSUE THREAD

**Issue by JuniorHP** [JunoLab/atom-julia-client#474]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Unknown Windows version
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.6.13

### Stack Trace

Uncaught Error: Cannot find module '../runtime'

```
At module.js:472

Error: Cannot find module '../runtime'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.1/resources/app/src/native-compile-cache.js:66:33)
    at workspace (/packages/julia-client/lib/ui/layout.js:69:10)
    at standard (/packages/julia-client/lib/ui/layout.js:94:17)
    at NotificationElement.onDidClick (/packages/julia-client/lib/ui/layout.js:13:9)
    at HTMLAnchorElement.<anonymous> (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/notifications/lib/notification-element.js:147:48)
```

### Commands

```
  3x -5:02.7.0 core:backspace (input.hidden-input)
     -4:39.6.0 core:confirm (input.hidden-input)
 24x -3:26.7.0 core:copy (div.panels-item)
  3x -2:06.0 core:confirm (input.hidden-input)
 21x -1:52.6.0 core:backspace (input.hidden-input)
     -1:44.4.0 core:confirm (input.hidden-input)
 13x -1:43.7.0 core:backspace (input.hidden-input)
     -1:30.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.2.1 
ink 0.8.5 
julia-client 0.6.13 
language-julia 0.16.0 
latex-completions 0.3.3 
tool-bar 1.1.7 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Something seems to have gone wrong with the installation here -- can you try reinstalling julia-client?
