### ISSUE TITLE
Failed to activate the julia-client package

### ISSUE THREAD

**Issue by mohamed82008** [JunoLab/atom-julia-client#495]
This is a reiteration of https://github.com/JunoLab/atom-julia-client/issues/270. Any idea what's happening here.

```julia
terminal.setTitle is not a function
Hide Stack Trace
TypeError: terminal.setTitle is not a function
    at Object.activate (file:///C:/Users/user/.atom/packages/julia-client/lib/runtime/console2.js:45:12)
    at Object.consumeInk (file:///C:/Users/user/.atom/packages/julia-client/lib/runtime.coffee:25:15)
    at Object.consumeInk (file:///C:/Users/user/.atom/packages/julia-client/lib/julia-client.coffee:43:7)
    at Provider.module.exports.Provider.provide (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\node_modules\service-hub\lib\provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\node_modules\service-hub\lib\service-hub.js:50:24)
    at Package.activateServices (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:405:79)
    at Package.activateNow (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:233:20)
    at measure (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package-manager.js:695:42)
    at config.transactAsync (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package-manager.js:670:36)
    at Config.transactAsync (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\config.js:866:28)
    at PackageManager.activatePackages (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package-manager.js:668:23)
    at PackageManager.activate (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\package-manager.js:647:50)
    at loadStatePromise.loadState.then (C:\Users\user\AppData\Local\atom\app-1.29.0\resources\app\src\atom-environment.js:871:27)
    at <anonymous>
```

**Comment by mohamed82008** [comment]
I am on Windows 10 and using latest Atom, 1.29.0.

**Comment by pfitzseb** [comment]
What versions of julia-client and ink do you have installed? The error message seems to indicate a mismatch -- it should be julia-client version 0.7.1 and ink version 0.9.2.

**Comment by mohamed82008** [comment]
these seem to be what I have.

**Comment by mohamed82008** [comment]
I deleted the .atom folder and reinstalled atom and uber-juno. Now I am getting something but not what I thought I would. When I run a line, the "settings" symbol shows up next to it. But I can't see the result. This is probably a different issue.

![image](https://user-images.githubusercontent.com/19524993/43819315-b192cade-9ae2-11e8-8a4d-af73882ac7b4.png)

**Comment by donaldRwilliams** [comment]
Hi:
I am having this same error, and wonder what the solution is.

**Comment by gdelvecchiodelvecchio** [comment]
I get the same error. Any idea ?


```
TypeError: terminal.setTitle is not a function
    at Object.activate (/home/giuseppe/.atom/packages/julia-client/lib/runtime/console2.js:47:12)
    at Object.consumeInk (/home/giuseppe/.atom/packages/julia-client/lib/runtime.coffee:26:15)
    at Object.consumeInk (/home/giuseppe/.atom/packages/julia-client/lib/julia-client.coffee:43:7)
    at Provider.module.exports.Provider.provide (/opt/atom/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/opt/atom/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.activateServices (/opt/atom/resources/app/src/package.js:405:79)
    at Package.activateNow (/opt/atom/resources/app/src/package.js:233:20)
    at measure (/opt/atom/resources/app/src/package.js:206:33)
    at Package.measure (/opt/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/opt/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/opt/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/opt/atom/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/opt/atom/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/opt/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/opt/atom/resources/app/src/atom-environment.js:871:27)
    at <anonymous>``
```
I have just installed Julia 1.0.1 and deleted the last version.

**Comment by pfitzseb** [comment]
You seem to be on an old version of ink -- please update and restart Atom.

**Comment by gdelvecchiodelvecchio** [comment]
Super nice! Just to understand: how did you get this from the errors?
Thanks!

**Comment by pfitzseb** [comment]
I know the code pretty well ;)

**Comment by gdelvecchiodelvecchio** [comment]
You'll be a reference, then ;)
