### ISSUE TITLE
Julia not able to start

### ISSUE THREAD

**Issue by naushad-rahman** [JunoLab/atom-julia-client#513]
my terminal is stuck in 
![image](https://user-images.githubusercontent.com/4056248/45251223-0dde0600-b375-11e8-9355-699fc7acd486.png)

![image](https://user-images.githubusercontent.com/4056248/45251226-1c2c2200-b375-11e8-9b95-dfa9f553e19f.png)

**Comment by SebastianM-C** [comment]
Do you have another window open?
I also encountered this when I open another project. (In the second project it hangs)

**Comment by pfitzseb** [comment]
What OS are you on? Are all Atom and Julia packages up to date?

Can you open the devtools (`Ctrl-Shift-I` or `Cmd-Shift-I`) and report any errors you might find there?

**Comment by hadirga** [comment]
Terminal in Juno is not running.

Toogle Developer Tools Error Message->
`Uncaught (in promise) Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
    at new WindowsPtyAgent (C:\Users\User\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\User\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:45:24)
    at Object.spawn (C:\Users\User\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\index.js:27:12)
    at file:///C:/Users/User/.atom/packages/julia-client/lib/connection/process/basic2.js:84:26
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
