### ISSUE TITLE
Uncaught TypeError: this.ink.Opener.allowRemoteFiles is not a function

### ISSUE THREAD

**Issue by skanskan** [JunoLab/atom-julia-client#535]
[Enter steps to reproduce:]

I've upgraded the julia-client package on Juno to 0.7.11 and when I start Juno I get this error:

**Atom**: 1.34.0-beta0 x64
**Electron**: 2.0.14
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.7.11

### Stack Trace

Uncaught TypeError: this.ink.Opener.allowRemoteFiles is not a function

```
At C:\Users\joe\.atom\packages\julia-client\lib\connection.coffee:44

TypeError: this.ink.Opener.allowRemoteFiles is not a function
    at Object._boot (/packages/julia-client/lib/connection.coffee:44:21)
    at Object.boot (/packages/julia-client/lib/connection.coffee:56:6)
    at Object.boot (/packages/julia-client/lib/connection.coffee:18:24)
    at InkTerminal.terminal.startRequested (/packages/julia-client/lib/runtime/console2.js:54:12)
    at InkTerminal.enterhandler (/packages/ink/lib/console2/console.js:84:16)
    at Terminal._customKeyEventHandler (/packages/ink/lib/console2/console.js:149:21)
    at Terminal._keyDown (/packages/ink/node_modules/xterm/lib/Terminal.js:948:49)
    at /packages/ink/node_modules/xterm/lib/Terminal.js:384:115)
```

### Commands

```
     -1:13.5.0 core:confirm (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
indent-detective 0.3.0 
ink 0.9.12 
julia-client 0.7.11 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
You're on an old version of atom-ink. Please update and restart.
