### ISSUE TITLE
Uncaught Error: Pty seems to have been killed already

### ISSUE THREAD

**Issue by VoSiLk** [JunoLab/atom-julia-client#559]
[Enter steps to reproduce:]

1. update to the latest atom julia version
2. start julia repl
3. stop julia repl

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: PRZCV0111
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.8.5

### Stack Trace

Uncaught Error: Pty seems to have been killed already

```
At C:\Users\k582186\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:83

Error: Pty seems to have been killed already
    at WindowsPtyAgent.kill (/packages/julia-client/node_modules/node-pty-prebuilt/lib/windowsPtyAgent.js:83:13)
    at /packages/julia-client/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:144:26)
    at WindowsTerminal._defer (/packages/julia-client/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:155:24)
    at WindowsTerminal.kill (/packages/julia-client/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:139:14)
    at /packages/julia-client/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:134:19)
    at WindowsTerminal._defer (/packages/julia-client/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:155:24)
    at WindowsTerminal.destroy (/packages/julia-client/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:133:14)
    at InkTerminal.detach (/packages/ink/lib/console2/console.js:207:15)
    at /packages/julia-client/lib/runtime/console2.js:98:14
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:1174290)
    at Emitter.emit (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:1175731)
    at Object.detach (/packages/julia-client/lib/connection/client.coffee:115:14)
    at /packages/julia-client/lib/connection/local.coffee:82:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -1:18.1.0 julia-debug:open-debugger-pane (input.hidden-input)
  2x -1:10.7.0 julia-client:run-file (atom-pane.pane)
     -1:06.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:06.7.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
     -0:58.6.0 julia-client:open-console (atom-pane.pane.active)
     -0:11.4.0 julia-client:kill-julia (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.3.2 
ink 0.10.7 
julia-client 0.8.5 
language-julia 0.18.1 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/bb70f71018269a37c3396543030d67716351d773.

**Comment by VolkerSmits** [comment]
Thanks. It works. But I have another issue. The debugger doesn´t stop at the breakpoints anymore since the update of the atom julia client. Shall I post it as a new issue of the atom-julia-client?

**Comment by pfitzseb** [comment]
Did you update your Julia packages to the version specified in [here](https://discourse.julialang.org/t/ann-juno-0-8-7/24682)?

**Comment by VolkerSmits** [comment]
No, not all. Somehow I can´t update Atom.jl via Pkg, because it doesn´t find a newer version

I´m working on
    julia-client version 0.8.5
    ink version 0.10.8
    Atom.jl version 0.8.5
    Juno.jl version 0.7.0

Do you know how I can update it? Also tried it with the apm update command in the terminal.

**Comment by pfitzseb** [comment]
You probably can update once https://github.com/JuliaRegistries/General/pull/1037 is merged (or temporarily uninstall Revise.jl).

**Comment by VolkerSmits** [comment]
I tried it, but it hasn´t an effect.

**Comment by pfitzseb** [comment]
First try a `pkg> up`, and then, if you still don't get the new Atom.jl version, try `pkg> add Atom@0.8.6` or `pkg> add JuliaInterpreter@0.6`. That should tell you what package is holding the update back.

**Comment by VolkerSmits** [comment]
I tried all of your tips. There were several dependencies, so that I decided to delete the .julia folder and  load the packages again via the package manager. It worked for me really good, but I hadn´t so much packages, so that it wasn´t so much work for me.

**Comment by efmanu** [comment]
I also tried above steps... I am also getting error while trying to stop Julia by using CTRL+J CTRL+K. The error is as follows:
```
Error: Pty seems to have been killed already
    at WindowsPtyAgent.kill (C:\Users\manu\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:160:29)
    at WindowsTerminal.<anonymous> (C:\Users\manu\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:148:26)
    at WindowsTerminal._defer (C:\Users\manu\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:155:24)
    at WindowsTerminal.kill (C:\Users\manu\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:143:14)
    at Object.kill (file:///C:/Users/manu/.atom/packages/julia-client/lib/connection/process/basic.js:125:20)
    at Socket.<anonymous> (file:///C:/Users/manu/.atom/packages/julia-client/lib/connection/local.coffee:77:12)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

How can I solve it?

**Comment by evveric** [comment]
I have the same error. When I read a large CSV file:

CSV.read(xxx) |> DataFrame

and then i want to CTRL-J CTRL-K to kill Julia process:

C:\Users\ericche\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:160

Error: Pty seems to have been killed already
    at WindowsPtyAgent.kill (C:\Users\ericche\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:160:29)
    at WindowsTerminal.<anonymous> (C:\Users\ericche\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:148:26)
    at WindowsTerminal._defer (C:\Users\ericche\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:155:24)
    at WindowsTerminal.kill (C:\Users\ericche\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:143:14)
    at Object.kill (file:///C:/Users/ericche/.atom/packages/julia-client/lib/connection/process/basic.js:125:20)
    at Socket.<anonymous> (file:///C:/Users/ericche/.atom/packages/julia-client/lib/connection/local.coffee:77:12)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)


I am using 
julia-client 0.12.2
ink 0.12.2
julia 1.3.1
atom 1.44.0 x64
windows 10

**Comment by LasseKatten** [comment]
I get the same error

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Windows 10 
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.12.2


### Stack Trace

Uncaught Error: Pty seems to have been killed already

```
At C:\Users\USER\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:160

Error: Pty seems to have been killed already
    at WindowsPtyAgent.kill (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsPtyAgent.js:160:29)
    at /packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:148:26)
    at WindowsTerminal._defer (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:155:24)
    at WindowsTerminal.kill (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:143:14)
    at Object.kill (/packages/julia-client/lib/connection/process/basic.js:125:20)
    at Object.clientCall (/packages/julia-client/lib/connection/client.coffee:138:7)
    at Object.kill (/packages/julia-client/lib/connection/client.coffee:158:10)
    at /packages/julia-client/lib/package/commands.coffee:129:60)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:764636)
    at EventEmitter.t (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:772559)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
  2x -6:26 julia-client:copy-or-interrupt (textarea.xterm-helper-textarea)
     -5:52.4.0 ink-terminal:paste (textarea.xterm-helper-textarea)
  2x -5:49.8.0 julia-client:copy-or-interrupt (textarea.xterm-helper-textarea)
  2x -2:58 julia-client:kill-julia (input.hidden-input)
     -2:09.0 julia-client:run-all (input.hidden-input)
     -2:09.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:09.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
     -1:20.3.0 core:copy (input.hidden-input)
     -1:18.4.0 editor:newline (input.hidden-input)
     -1:18 core:paste (input.hidden-input)
     -1:17.7.0 editor:newline (input.hidden-input)
     -1:15.7.0 core:backspace (input.hidden-input)
  3x -1:14.8.0 core:move-down (input.hidden-input)
     -1:13.9.0 core:backspace (input.hidden-input)
     -1:13.7.0 core:save (input.hidden-input)
  2x -1:10.7.0 julia-client:kill-julia (input.hidden-input)
```

### Non-Core Packages

```
atom-dark-fusion-syntax 2.2.1 
cobalt2-syntax 0.5.3 
cobolt-atom-theme 0.3.3 
indent-detective 0.4.0 
ink 0.12.2 
julia-client 0.12.2 
language-julia 0.19.2 
latex-completions 0.3.6 
tool-bar 1.2.0 
uber-juno 0.3.0 
```

**Comment by evveric** [comment]
> I get the same error
> 
> **Atom**: 1.44.0 x64
> **Electron**: 4.2.7
> **OS**: Windows 10
> **Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.12.2
> 
> ### Stack Trace
> Uncaught Error: Pty seems to have been killed already
> 
> ```
> At C:\Users\USER\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:160
> 
> Error: Pty seems to have been killed already
>     at WindowsPtyAgent.kill (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsPtyAgent.js:160:29)
>     at /packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:148:26)
>     at WindowsTerminal._defer (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:155:24)
>     at WindowsTerminal.kill (/packages/julia-client/node_modules/node-pty-prebuilt-multiarch/lib/windowsTerminal.js:143:14)
>     at Object.kill (/packages/julia-client/lib/connection/process/basic.js:125:20)
>     at Object.clientCall (/packages/julia-client/lib/connection/client.coffee:138:7)
>     at Object.kill (/packages/julia-client/lib/connection/client.coffee:158:10)
>     at /packages/julia-client/lib/package/commands.coffee:129:60)
>     at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:349290)
>     at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:347765)
>     at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:764636)
>     at EventEmitter.t (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:772559)
>     at EventEmitter.emit (events.js:182:13)
> ```
> 
> ### Commands
> ```
>   2x -6:26 julia-client:copy-or-interrupt (textarea.xterm-helper-textarea)
>      -5:52.4.0 ink-terminal:paste (textarea.xterm-helper-textarea)
>   2x -5:49.8.0 julia-client:copy-or-interrupt (textarea.xterm-helper-textarea)
>   2x -2:58 julia-client:kill-julia (input.hidden-input)
>      -2:09.0 julia-client:run-all (input.hidden-input)
>      -2:09.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
>      -2:09.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
>      -1:20.3.0 core:copy (input.hidden-input)
>      -1:18.4.0 editor:newline (input.hidden-input)
>      -1:18 core:paste (input.hidden-input)
>      -1:17.7.0 editor:newline (input.hidden-input)
>      -1:15.7.0 core:backspace (input.hidden-input)
>   3x -1:14.8.0 core:move-down (input.hidden-input)
>      -1:13.9.0 core:backspace (input.hidden-input)
>      -1:13.7.0 core:save (input.hidden-input)
>   2x -1:10.7.0 julia-client:kill-julia (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> ```
> atom-dark-fusion-syntax 2.2.1 
> cobalt2-syntax 0.5.3 
> cobolt-atom-theme 0.3.3 
> indent-detective 0.4.0 
> ink 0.12.2 
> julia-client 0.12.2 
> language-julia 0.19.2 
> latex-completions 0.3.6 
> tool-bar 1.2.0 
> uber-juno 0.3.0 
> ```

May I know how to generate this "Stack Trace", "Commands" and "non core package" ?

**Comment by LasseKatten** [comment]
> May I know how to generate this "Stack Trace", "Commands" and "non core package" ?

You can see in the attached image where I got it from 

![help](https://user-images.githubusercontent.com/49748737/75767381-0073c300-5d43-11ea-8fb7-16e1f42661db.png)

**Comment by evveric** [comment]
> > May I know how to generate this "Stack Trace", "Commands" and "non core package" ?
> 
> You can see in the attached image where I got it from
> 
> ![help](https://user-images.githubusercontent.com/49748737/75767381-0073c300-5d43-11ea-8fb7-16e1f42661db.png)
> 
> I assume you get the same error popup in atom

nice one, thanks!

**Comment by nilshg** [comment]
Just to confirm that I'm getting the same when reading a large CSV file - not always, but most of the time. Julia just freezes, with little to no CPU usage, and all I can do is completely close down Atom. At times though the CSV read succeeds, so maybe there's an issue related to threading here (given that CSV.read is multithreaded now afaik)?

**Comment by LasseKatten** [comment]
> nice one, thanks!

You can also get more info by following the steps outlined in the attached image
![help](https://user-images.githubusercontent.com/49748737/75877424-fd96d200-5e17-11ea-85f2-c5334f0e98ea.png)

It will show you every setting, package, version etc. that you have.

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/JunoLab/atom-julia-client/pull/699.
