### ISSUE TITLE
Uncaught TypeError: selector.show is not a function

### ISSUE THREAD

**Issue by grahamgill** [JunoLab/atom-julia-client#572]
Steps to reproduce:

1. From Julia menu in Atom, select Working Directory -> Current Project's Folder
2. That's it. I had a current project in the Projects pane, and another non-current project in the pane also.

Other selections
* Working Directory -> Current File's Folder
* Working Directory -> Home Folder
work correctly, as confirmed with 'pwd' from Julia REPL shell prompt.

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.8.10

### Stack Trace

Uncaught TypeError: selector.show is not a function

```
At C:\Users\Graham\.atom\packages\julia-client\lib\runtime\evaluation.coffee:138

TypeError: selector.show is not a function
    at Object.cdProject (/packages/julia-client/lib/runtime/evaluation.coffee:138:16)
    at /packages/julia-client/lib/package/commands.coffee:126:35
    at Object.require (/packages/julia-client/lib/connection/client.coffee:193:30)
    at requireClient (/packages/julia-client/lib/package/commands.coffee:7:57)
    at /packages/julia-client/lib/package/commands.coffee:125:9)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:348418)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:346893)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:1:719216)
    at EventEmitter.t (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:1:727139)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  2x -4:58.9.0 editor:newline (input.hidden-input)
  2x -4:53.2.0 core:move-down (input.hidden-input)
     -4:52.7.0 autocomplete-plus:confirm (input.hidden-input)
     -4:50.3.0 core:backspace (input.hidden-input)
     -4:48.7.0 core:move-right (input.hidden-input)
     -4:45.5.0 core:save (input.hidden-input)
     -4:28.1.0 julia-client:run-block (input.hidden-input)
     -4:28.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -4:16.4.0 core:select-all (input.hidden-input)
     -4:14.4.0 julia-client:run-block (input.hidden-input)
     -4:14.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -2:10.2.0 julia-client:run-block (input.hidden-input)
     -2:10.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:27.9.0 julia-client:work-in-project-folder (textarea.xterm-helper-textarea)
     -0:53 application:add-project-folder (span.name.icon.icon-repo)
     -0:24.1.0 julia-client:work-in-project-folder (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
indent-detective 0.3.3 
ink 0.10.11 
julia-client 0.8.10 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Hm, I can't reproduce this. Did you by chance update your Atom packages and not restart Atom? Can you reproduce the issue after a restart?

**Comment by grahamgill** [comment]
Indeed that was the problem. It works after a restart. Forgot that I had reinstalled julia-client a few days ago.
