### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenizeLines' of undefined

### ISSUE THREAD

**Issue by baggepinnen** [JunoLab/atom-julia-client#586]
I just updated atom, julia packages, atom packages

1. I just tried to run a line in the editor
2. The problem only appears if the cursor is in a block and I press ctrl-enter. If I mark the block and evaluate, it works. It also works to evaluate a single line.

Debug info below

# Atom:
Version: 1.39.1
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.9.2
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "bootMode": "Basic",
    "numberOfThreads": "3"
  },
  "juliaPath": "julian",
  "uiOptions": {
    "enableMenu": true,
    "layouts": {
      "console": {
        "defaultLocation": "center",
        "split": "right"
      },
      "defaultPanes": {
        "workspace": false,
        "documentation": false,
        "plotPane": false
      },
      "plotPane": {
        "split": "up"
      },
      "terminal": {
        "defaultLocation": "center",
        "split": "right"
      },
      "workspace": {
        "defaultLocation": "right",
        "split": "no split"
      }
    }
  }
}

# ink:
Version: 0.10.12
Config:
undefined

# uber-juno:
Version: 0.2.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.1
Config:
undefined

# language-weave:
Version: 0.6.4
Config:
undefined

# indent-detective:
Version: 0.4.0
Config:
undefined

Julia Version 1.3.0-alpha.0
Commit 6c11e7c2c4 (2019-07-23 01:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4550U CPU @ 1.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 3
  JULIA_EDITOR = atom  -a

    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.9.0
  [70b36510] AutomaticDocstrings v0.1.1
  [07f847a3] BasisFunctionExpansions v1.0.1
  [6e4b80f9] BenchmarkTools v0.4.2
  [7057c7e9] Cassette v0.2.6
  [a6e380b2] ControlSystems v0.5.3 [`~/.julia/dev/ControlSystems`]
  [f68482b8] Cthulhu v0.1.1 [`~/.julia/dev/Cthulhu`]
  [717857b8] DSP v0.5.2
  [9cd584b6] DifferentialDynamicProgramming v0.4.0 [`~/.julia/dev/DifferentialDynamicProgramming`]
  [0c46a032] DifferentialEquations v6.6.0
  [31c24e10] Distributions v0.20.0
  [5789e2e9] FileIO v1.0.7
  [587475ba] Flux v0.8.3
  [f6369f11] ForwardDiff v0.10.3
  [28b8d3ca] GR v0.41.0
  [f67ccb44] HDF5 v0.12.0
  [174f11e0] Hydra v0.1.0 #master (https://github.com/FluxML/Hydra.jl)
  [7869d1d1] IRTools v0.2.2
  [033835bb] JLD2 v0.1.2
  [e5e0dc1b] Juno v0.7.1
  [26dcc766] LPVSpectral v0.1.3
  [98b081ad] Literate v2.0.2
  [43172d54] LiterateWeave v0.1.0 [`~/.julia/dev/LiterateWeave`]
  [15d4e49f] LowRankModels v1.0.1 [`~/.julia/dev/LowRankModels`]
  [33e6dc65] MKL v0.0.0 #master (https://github.com/JuliaComputing/MKL.jl)
  [f0e99cf1] MLBase v0.8.0
  [cc2ba9b6] MLDataUtils v0.5.0
  [0987c9cc] MonteCarloMeasurements v0.4.0 [`~/.julia/dev/MonteCarloMeasurements`]
  [872c559c] NNlib v0.6.0
  [1dea7af3] OrdinaryDiffEq v5.14.0
  [58dd65bb] Plotly v0.2.0
  [f0f68f2c] PlotlyJS v0.12.5
  [91a5bcdd] Plots v0.25.3
  [d330b81b] PyPlot v2.8.1
  [1fd47b50] QuadGK v2.1.0
  [f535d66d] ROCAnalysis v0.3.0
  [295af30f] Revise v2.1.6
  [a75dfa10] Robotlib v0.3.2+ [`~/.julia/dev/Robotlib`]
  [90137ffa] StaticArrays v0.11.0
  [4c63d2b9] StatsFuns v0.8.0
  [f3b207a7] StatsPlots v0.11.0
  [37b6cedf] Traceur v0.3.0
  [8149f6b0] WAV v1.0.2
  [44d3d7a6] Weave v0.9.1
  [e88e6eb3] Zygote v0.3.2

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.2
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.9.2

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenizeLines' of undefined

```
At /home/fredrikb/.atom/packages/julia-client/lib/misc/scopes.js:32

TypeError: Cannot read property 'tokenizeLines' of undefined
    at forRange (/packages/julia-client/lib/misc/scopes.js:32:16)
    at Object.forLines (/packages/julia-client/lib/misc/scopes.js:69:10)
    at Object.walkForward (/packages/julia-client/lib/misc/blocks.coffee:30:24)
    at Object.moveNext (/packages/julia-client/lib/misc/blocks.coffee:65:11)
    at /packages/julia-client/lib/runtime/evaluation.coffee:33:16
    at Array.map (<anonymous>)
    at Object.eval (/packages/julia-client/lib/runtime/evaluation.coffee:32:38)
    at /packages/julia-client/lib/package/commands.coffee:27:13
    at Object.withInk (/packages/julia-client/lib/package/commands.coffee:140:7)
    at /packages/julia-client/lib/package/commands.coffee:25:12)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:283942)
```

### Commands

```
     -2:27 editor:newline (input.hidden-input)
     -2:26.4.0 core:paste (input.hidden-input)
  3x -2:26.2.0 core:backspace (input.hidden-input)
     -2:24.5.0 core:save (input.hidden-input)
     -2:23.6.0 editor:newline (input.hidden-input)
     -2:20.6.0 core:save (input.hidden-input)
     -2:09.4.0 julia-client:run-block (input.hidden-input)
     -2:09.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -1:48.3.0 julia-client:show-documentation (span.syntax--entity.syntax--name.syntax--function.syntax--julia)
  2x -1:35.6.0 editor:newline (input.hidden-input)
  2x -1:30.7.0 core:move-down (input.hidden-input)
     -1:30 autocomplete-plus:confirm (input.hidden-input)
     -1:16.7.0 command-palette:toggle (input.hidden-input)
     -1:13.9.0 core:confirm (input.hidden-input)
     -1:13.8.0 julia-client:settings (input.hidden-input)
     -0:14 julia-client:run-and-move (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-ide-datatip 0.11.0 
atom-ide-markdown-service 1.2.3 
auto-indent 0.5.0 
busy-signal 2.0.1 
file-icons 2.1.33 
highlight-selected 0.16.0 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.10.12 
julia-client 0.9.2 
language-julia 0.19.1 
language-latex 1.2.0 
language-weave 0.6.4 
latex 0.50.2 
latex-completions 0.3.6 
markdown-pdf 2.2.0 
markdown-preview-plus 3.9.3 
open-in-browser 0.5.2 
pdf-view 0.71.0 
project-manager 3.3.7 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by AshtonSBradley** [comment]
yeah, normal shift+enter evaluation is broken

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/atom-julia-client/commit/f3d7ef72d40a05b5b88fb7e43ec09f17804d2886.

**Comment by alicecorbella** [comment]
Hi, thanks for fixing this, though I am not sure what shall I do not to have that error anymore!

**Comment by pfitzseb** [comment]
You can't really do anything aboout this atm, but I'll release a new version in a couple of minutes. Upgrading to that will fix the bug for you.

**Comment by alicecorbella** [comment]
Thanks a lot for this!!!
