### ISSUE TITLE
Julia-client 0.9.4 install error

### ISSUE THREAD

**Issue by ChrisNabold** [JunoLab/atom-julia-client#590]
I upgraded atom from V1.38.1 to V1.40 and upgraded Julia-client to V.0.9.4. Now Julia-client can no longer be installed
prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Chris\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Chris\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Chris\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Chris\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Chris\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\Chris\.atom\packages\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\.atom\.apm\_logs\2019-08-14T05_55_39_737Z-debug.log

**Comment by Jones-IHF** [comment]
Exactly the same bug here, find complete log here: 
https://pastebin.com/H7vRLDgJ

**Comment by pfitzseb** [comment]
This appears to be the same issue we had when Atom 1.39 was released, so I’m very surprised that the fix for that doesn’t work for some people.

Do you have any weird antivir software running that might delete the binaries we ship, so that we then try to compile them ourselves? I can’t reproduce this issue anymore on a fairly clean Windows VM.

[Same issue as here](https://discourse.julialang.org/t/atom-1-39-wont-build-julia-client/26696).

**Comment by ChrisNabold** [comment]
Dear Sebastian,

 

I use Windows 10 (latest version) / 64 bit. My antivirus is Microsoft Defender. I had the problem already with version 1.39.0 ( I did not try version 1.39.1)

I decided to wait for the 1.40 version Atom. 

When I upgraded to Atom version 1.40 Atom offered upgrades also for Julia Client 0.9.4

 

Thank you for your help

Chris Nabold

**Comment by Donquicote** [comment]
Same issue in Mac OSX 10.14.6

**Comment by W-J-Trenberth** [comment]
Same issue in Ubuntu 18.04.

**Comment by pfitzseb** [comment]
See [here](https://discourse.julialang.org/t/juno-fails-to-install-julia-client-0-9-4/27544/8?u=pfitzseb) for updates on this.

**Comment by alex007javier** [comment]
Same issue...

**Comment by alex007javier** [comment]
What I can do ? 

Starting Julia...
ERROR: LoadError: IOError: stat: operation not permitted (EPERM)
Stacktrace:
 [1] stat(::String) at .\stat.jl:68
 [2] ispath at .\stat.jl:303 [inlined]
 [3] (::getfield(Base, Symbol("##645#646")){String,Base.PkgId})(::IOStream) at .\loading
 [4] #open#294(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, :
:getfield(Base, Symbol("##645#646")){String,Base.PkgId}, ::String) at .\iostream.jl:369
 [5] open at .\iostream.jl:367 [inlined]
 [6] explicit_manifest_uuid_path at .\loading.jl:520 [inlined]
ERROR: LoadError: IOError: stat: operation not permitted (EPERM)
Stacktrace:
 [1] stat(::String) at .\stat.jl:68
 [2] ispath at .\stat.jl:303 [inlined]
 [3] (::getfield(Base, Symbol("##645#646")){String,Base.PkgId})(::IOStream) at .\loading
 [4] #open#294(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, :
 [5] open at .\iostream.jl:367 [inlined]
 [6] explicit_manifest_uuid_path at .\loading.jl:520 [inlined]
 [7] manifest_uuid_path(::String, ::Base.PkgId) at .\loading.jl:324
 [8] locate_package(::Base.PkgId) at .\loading.jl:245
 [9] stale_cachefile(::String, ::String) at .\loading.jl:1351
 [10] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:693
 [11] _require(::Base.PkgId) at .\loading.jl:937
 [12] require(::Base.PkgId) at .\loading.jl:858
 [13] require(::Module, ::Symbol) at .\loading.jl:853
 [14] top-level scope at C:\Users\javie\.atom\packages\julia-client\script\boot_repl.jl:31 [15] include at .\boot.jl:317 [inlined]
 [16] include_relative(::Module, ::String) at .\loading.jl:1044
 [17] include(::Module, ::String) at .\sysimg.jl:29
 [18] exec_options(::Base.JLOptions) at .\client.jl:266
 [19] _start() at .\client.jl:425
in expression starting at C:\Users\javie\.atom\packages\julia-client\script\boot_repl.jl:1

**Comment by Jones-IHF** [comment]
What worked for me:

1. Go in to `C:/Users/*/AppData/Local/atom` and delete atom-1.40, assuming 1.39 is still there
2. delete C:/Users/*/.atom
3. Reinstall packages

**Comment by aviatesk** [comment]
This issue now should be fixed with the release of Atom v1.40.1: https://atom.io
