### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by zygmuntszpak** [JunoLab/atom-julia-client#64]
[Enter steps to reproduce below:]
I completed the installation instruction described here: https://github.com/JunoLab/atom-julia-client/tree/master/manual

And have the following packages installed:
julia> Pkg.status()
1 required packages:
 - Atom                          0.2.0
11 additional packages:
 - CodeTools                     0.2.0
 - Compat                        0.7.7
 - FactCheck                     0.4.1
 - Hiccup                        0.0.1
 - JSON                          0.5.0
 - JuliaParser                   0.6.3+             master
 - LNR                           0.0.2
 - Lazy                          0.10.1
 - MacroTools                    0.2.0
 - Media                         0.1.1
 - Requires                      0.2.1

0. Start with a blank document.
1.  From command palette select *Julia: Open Julia Home*
2. Similar errors occur when selecting: *Julia: Open Startup File*
  

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.1.2

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:190

TypeError: Arguments to path.join must be strings
    at f (path.js:190:13)
    at Object.filter (native)
    at Object.win32.join (path.js:195:38)
    at Object.module.exports.home (file:///C:/Users/szpakz/.atom/packages/julia-client/lib/utils.coffee:14:19)
    at Object.module.exports.juliaHome (file:///C:/Users/szpakz/.atom/packages/julia-client/lib/utils.coffee:16:44)
    at atom-workspace.subs.add.atom.commands.add.julia:open-julia-home (file:///C:/Users/szpakz/.atom/packages/julia-client/lib/utils.coffee:62:51)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\szpakz\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
    at C:\Users\szpakz\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\szpakz\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\szpakz\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
```

### Commands

```
     -2:39.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:34.2.0 julia-client:start-julia (atom-text-editor.editor)
     -0:09.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.7.0 julia:open-julia-home (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  },
  "julia-client": {}
}
```

### Installed Packages

```coffee
# User
ink, v0.1.1
julia-client, v0.1.2
language-julia, v0.4.1
latex-completions, v0.3.0

# Dev
No dev packages
```

**Comment by Varanas** [comment]
Can't reproduce on master.
If you don't want to wait for the next tagged version (which should be out soon, I think), then follow the [dev-install instructions](https://github.com/JunoLab/atom-julia-client/tree/master/docs).

**Comment by one-more-minute** [comment]
Yup, seems to be fine on master. Let me know if you're still seeing it there.
