### ISSUE TITLE
Failed to activate the julia-client package

### ISSUE THREAD

**Issue by StevenCarte** [JunoLab/atom-julia-client#656]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.11.3

### Stack Trace

Failed to activate the julia-client package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1215455)
    at CompositeDisposable.add (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1216423)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:162456)
    at Object.consumeProvider_4 (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:162264)
    at Provider.provide (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1125283)
    at ServiceHub.provide (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3308382)
    at Package.activateServices (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3316668)
    at Package.activateNow (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3313644)
    at measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3312968)
    at Package.measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3310578)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3312828)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3312771)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:382554)
    at o.forEach.e (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:377720)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:377704)
    at emitter.on (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:334755)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:337243)
    at Config.setRawValue (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:334483)
    at Config.set (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:330277)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:332300)
    at Package.enable (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3310363)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:375418)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2603767)
```

### Commands

```
     -0:41.9.0 julia:get-help (input.hidden-input)
     -0:36.1.0 julia-client:settings (input.hidden-input)
```

### Non-Core Packages

```
atom-julia-run 1.0.5 
busy-signal 2.0.1 
gfm-pdf 0.3.5 
indent-detective 0.4.0 
ink 0.11.6 
intentions 1.1.5 
julia-client 0.11.3 
language-julia 0.19.1 
latex-completions 0.3.6 
linter 2.3.1 
linter-julia 0.7.4 
linter-ui-default 1.8.0 
notes-from-pdf 0.4.2 
pdf-view 0.72.0 
script 3.25.0 
tool-bar 1.2.0 
uber-juno 0.3.0 
```

**Comment by mantzaris** [comment]
I have the same issue on Debian

**Comment by pfitzseb** [comment]
Even after a restart of Atom?

**Comment by eirikeb** [comment]
I have the same issue using Pop!_os (What a horrible name for an OS, but I digress).

....
```
Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.loadNative (/home/eirik/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/utils.js:22:16)
    at Object.<anonymous> (/home/eirik/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:24:19)
    at Object.<anonymous> (/home/eirik/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:255:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/home/eirik/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:14:20)
    at Object.<anonymous> (/home/eirik/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:52:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/home/eirik/.atom/packages/julia-client/lib/connection/process/basic.js:3:24)
    at Object.<anonymous> (/home/eirik/.atom/packages/julia-client/lib/connection/process/basic.js:186:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
```
Happened after I updated a bunch of software, including Atom. 

Tried restarting atom as well as rebooting the computer.

**Comment by mantzaris** [comment]
> Even after a restart of Atom?

Yes, and it persists

**Comment by jonniedie** [comment]
Still happening for me.

**Comment by sth4nth** [comment]
When will this be fixed. This happened with fresh OS install.

**Comment by aviatesk** [comment]
Reinstall or rebuild julia-client pkg as the doc says:
http://docs.junolab.org/latest/man/faq/#Juno-doesn't-work-properly-after-an-Atom-update.-What-do-I-do?-1

Make sure you restart Atom after reinstalling.

**Comment by sth4nth** [comment]
With fresh OS, julia-client does not even install. How can I rebuild?
Installing “julia-client@0.11.3” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0 install C:\Users\mo\AppData\Local\Temp\apm-install-dir-1191120-2316-46hx7d.schsh\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


C:\Users\mo\AppData\Local\Temp\apm-install-dir-1191120-2316-46hx7d.schsh\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\mo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\mo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install unexpected end of file
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\mo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\mo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\mo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\mo\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\mo\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mo\AppData\Local\Temp\apm-install-dir-1191120-2316-46hx7d.schsh\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\mo\AppData\Local\Temp\apm-install-dir-1191120-2316-46hx7d.schsh\package.json'
npm WARN apm-install-dir-1191120-2316-46hx7d.schsh No description
npm WARN apm-install-dir-1191120-2316-46hx7d.schsh No repository field.
npm WARN apm-install-dir-1191120-2316-46hx7d.schsh No README data
npm WARN apm-install-dir-1191120-2316-46hx7d.schsh No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mo\.atom\.apm\_logs\2019-12-20T06_22_33_924Z-debug.log

**Comment by aviatesk** [comment]
seems like you are on older version of Atom

**Comment by sth4nth** [comment]
My Atom version is 1.41.0 x64 on win10. I have the same problem on both my laptop and desktop with fresh installed windows

**Comment by sth4nth** [comment]
I updated my Atom to 1.42.0, the problem is still the same. This problem is the with
https://github.com/JunoLab/atom-julia-client/issues/642#issuecomment-545891088

**Comment by sth4nth** [comment]
For Atom 1.44 with julia-client 0.12.2, this problem is gone.

**Comment by shakisparki** [comment]
Went away after updating ink to 0.12.2. Try updating all packages.

**Comment by spcogg** [comment]
updating ink fixed this to me. Probably occurs if you only update the julia packages without ink
