### ISSUE TITLE
Uncaught TypeError: log is not a function

### ISSUE THREAD

**Issue by sh-wszhao** [JunoLab/atom-julia-client#770]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Deepin 20
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.12.6

### Stack Trace

Uncaught TypeError: log is not a function

```
At /home/zhaows/.atom/packages/julia-client/lib/runtime/plots.js:17

TypeError: log is not a function
    at consoleLog (/packages/julia-client/lib/runtime/plots.js:17:3)
    at /packages/julia-client/lib/runtime/plots.js:112:48)
    at WebViewImpl.dispatchEvent (/usr/share/atom/resources/electron.asar/renderer/web-view/web-view-impl.js:100:26)
    at dispatchEvent (/usr/share/atom/resources/electron.asar/renderer/web-view/guest-view-internal.js:52:13)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/renderer/web-view/guest-view-internal.js:68:9)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/usr/share/atom/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -9:08.2.0 editor:newline (input.hidden-input)
     -8:56.1.0 julia-client:run-all (input.hidden-input)
     -8:56.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -8:56.1.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
     -8:19 editor:newline (input.hidden-input)
     -2:05.7.0 ink-terminal:copy (canvas.xterm-cursor-layer)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-file-icons 0.7.1 
atom-material-syntax 1.0.8 
atom-python-run 0.9.7 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
data-explorer 0.7.0 
highlight-selected 0.17.0 
Hydrogen 2.14.6 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
hyperclick 0.1.5 
ide-python 1.5.1 
indent-detective 0.4.0 
ink 0.12.5 
intentions 1.1.5 
Jude 0.2.9 
julia-client 0.12.6 
kite 0.195.0 
language-julia 0.20.0 
latex-completions 0.3.6 
linter 3.1.1 
linter-julia 0.8.3 
linter-ui-default 2.1.4 
minimap 4.29.9 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
python-debugger 0.2.0 
script 3.26.0 
tool-bar 1.4.1 
uber-juno 0.3.0 
```

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/409fc49abfb29d3cb1c24882d9de963bd3c83176.
