### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by ilyaamburg** [JunoLab/atom-julia-client#774]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.0.1
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.12.6

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At /Users/ilyaamburg/.atom/packages/julia-client/lib/runtime/console.js:350

TypeError: Cannot read property 'on' of undefined
    at /packages/julia-client/lib/runtime/console.js:350:18
    at /packages/julia-client/node_modules/ssh2/lib/client.js:1375:14
    at /packages/julia-client/node_modules/ssh2/lib/Channel.js:206:24)
    at SSH2Stream.emit (events.js:200:13)
    at parsePacket (/packages/julia-client/node_modules/ssh2-streams/lib/ssh.js:3255:10)
    at SSH2Stream._transform (/packages/julia-client/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (/packages/julia-client/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at SSH2Stream.Writable.write (_stream_writable.js:301:11)
    at Socket.ondata (_stream_readable.js:713:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

### Commands

```
  2x -0:35.2.0 pane:close (div.tool-panel.tree-view)
     -0:20.3.0 ftp-remote-edit:toggle (div.tool-panel.tree-view)
     -0:18.7.0 core:confirm (input.hidden-input)
     -0:03.5.0 julia-client:new-remote-terminal (div.ftp-remote-edit-view.ftp-remote-edit-resizer.tool-panel)
```

### Non-Core Packages

```
ftp-remote-edit 0.18.1 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.5 
julia-client 0.12.6 
language-julia 0.20.1 
latex-completions 0.3.6 
tool-bar 1.4.2 
uber-juno 0.3.0 
```

**Comment by helloinrm** [comment]
i'm having the same issue, just as shown above. any kindly suggestion?
