### ISSUE TITLE
Uncaught TypeError: log is not a function

### ISSUE THREAD

**Issue by CBongiova** [JunoLab/atom-julia-client#785]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.12.6
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.12.6

### Stack Trace

Uncaught TypeError: log is not a function

```
At /Users/admin/.atom/packages/julia-client/lib/runtime/plots.js:17

TypeError: log is not a function
    at consoleLog (/packages/julia-client/lib/runtime/plots.js:17:3)
    at /packages/julia-client/lib/runtime/plots.js:112:48)
    at WebViewImpl.dispatchEvent (electron/js2c/renderer_init.js:155:2221)
    at dispatchEvent (electron/js2c/renderer_init.js:143:1883)
    at electron/js2c/renderer_init.js:143:3008
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:127:872)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -2:17.5.0 core:paste (input.hidden-input)
  2x -1:53.8.0 core:save (input.hidden-input)
     -1:11.1.0 julia-client:run-block (input.hidden-input)
     -1:11.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:53.3.0 julia-client:run-block (input.hidden-input)
     -0:53.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:50.2.0 julia-client:run-block (input.hidden-input)
     -0:50.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:43.6.0 julia-client:run-block (input.hidden-input)
     -0:43.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:41.2.0 julia-client:run-block (input.hidden-input)
     -0:41.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection.hyperclick)
     -0:39.7.0 julia-client:run-block (input.hidden-input)
     -0:39.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:35.2.0 julia-client:run-block (input.hidden-input)
     -0:35.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
```

### Non-Core Packages

```
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.6 
julia-client 0.12.6 
juno-plus 0.13.1 
language-julia 0.21.2 
language-latex 1.2.0 
latex 0.50.2 
latex-completions 0.3.6 
tool-bar 1.4.4 
uber-juno 0.3.0 
```

**Comment by rrgalvan** [comment]
I had the same issue but it disappeared after typing:

```
using Pkg
Pkg.update()
```

**Comment by mashu** [comment]
That didn't solve the issue for me. It still happens.
