### ISSUE TITLE
Installing “julia-client@0.12.6” failed

### ISSUE THREAD

**Issue by 2226123114** [JunoLab/atom-julia-client#787]
Installing “julia-client@0.12.6” failed.[Hide output…]()

> node-pty-prebuilt-multiarch@0.9.0 install C:\Users\WJ&ZXY\AppData\Local\Temp\apm-install-dir-202223-16888-5dl9kq.0qp4n\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\WJ&ZXY\AppData\Local\Temp\apm-install-dir-202223-16888-5dl9kq.0qp4n\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\WJ&ZXY\AppData\Local\atom\app-1.59.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\WJ&ZXY\AppData\Local\atom\app-1.59.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

'ZXY\AppData\Local\Temp\apm-install-dir-202223-16888-5dl9kq.0qp4n\node_modules\julia-client\node_modules\.bin\' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'C:\Users\prebuild-install\bin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\WJ&ZXY\AppData\Local\atom\app-1.59.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\WJ&ZXY\AppData\Local\atom\app-1.59.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\WJ&ZXY\AppData\Local\atom\app-1.59.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\WJ&ZXY\AppData\Local\atom\app-1.59.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\WJ&ZXY\\AppData\\Local\\atom\\app-1.59.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\WJ&ZXY\\AppData\\Local\\atom\\app-1.59.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\WJ&ZXY\AppData\Local\Temp\apm-install-dir-202223-16888-5dl9kq.0qp4n\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\WJ&ZXY\AppData\Local\Temp\apm-install-dir-202223-16888-5dl9kq.0qp4n\package.json'
npm WARN apm-install-dir-202223-16888-5dl9kq.0qp4n No description
npm WARN apm-install-dir-202223-16888-5dl9kq.0qp4n No repository field.
npm WARN apm-install-dir-202223-16888-5dl9kq.0qp4n No README data
npm WARN apm-install-dir-202223-16888-5dl9kq.0qp4n No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WJ&ZXY\.atom\.apm\_

**Comment by 2226123114** [comment]
Did someone experience the same problem like mine?

**Comment by HannahMBeckmann** [comment]
I have it now. Did you solve it, and how?

**Comment by pfitzseb** [comment]
I recommend downgrading to an older version of Atom. It's unlikely this will be fixed (and Atom's package manager will stop working soon anyways).

**Comment by StefanPofahl** [comment]
On Ubuntu the rebuild was yesterday successful ...

**Comment by StefanPofahl** [comment]
I have now tested three older versions of atom:

- v1.63.0
- v1.60.0
- v1.38.2

no success. 
Maybe it is a better idea to work with the current version `v1.63.1` and an older version of `julia-client`.
But I do not know, how to do that ... :-(
apm install --help
is not very talkative ...

**Comment by StefanPofahl** [comment]
changing to 32-bit version of Atom failed as well ...

**Comment by pfitzseb** [comment]
Atom package management is broken. You probably should not expect it to come back up in the future due to [Atom being sunset by end of this week](https://github.blog/2022-06-08-sunsetting-atom/).

**Comment by StefanPofahl** [comment]
Unfortunately, I have not the skills to fix the issue on my own. I liked Atom a lot :-(
P.S.:
`emacs` is currently no option under MS-Windows ...
